const colors = {
  light: {
    text: '#0C1A2E',
    tint: '#0891B2',
    background: '#F0F9FF',
    foreground: '#0C1A2E',
    card: '#FFFFFF',
    cardForeground: '#0C1A2E',
    primary: '#0891B2',
    primaryForeground: '#FFFFFF',
    secondary: '#E0F2FE',
    secondaryForeground: '#0C4A6E',
    muted: '#E0F2FE',
    mutedForeground: '#64748B',
    accent: '#F59E0B',
    accentForeground: '#FFFFFF',
    destructive: '#EF4444',
    destructiveForeground: '#FFFFFF',
    success: '#10B981',
    successForeground: '#FFFFFF',
    warning: '#F59E0B',
    warningForeground: '#FFFFFF',
    border: '#BAE6FD',
    input: '#E0F2FE',
    ring: '#0891B2',
  },
  dark: {
    text: '#F0F9FF',
    tint: '#22D3EE',
    background: '#0C1A2E',
    foreground: '#F0F9FF',
    card: '#132337',
    cardForeground: '#F0F9FF',
    primary: '#22D3EE',
    primaryForeground: '#0C1A2E',
    secondary: '#1E3A5F',
    secondaryForeground: '#BAE6FD',
    muted: '#1E3A5F',
    mutedForeground: '#94A3B8',
    accent: '#F59E0B',
    accentForeground: '#FFFFFF',
    destructive: '#EF4444',
    destructiveForeground: '#FFFFFF',
    success: '#10B981',
    successForeground: '#FFFFFF',
    warning: '#F59E0B',
    warningForeground: '#FFFFFF',
    border: '#1E3A5F',
    input: '#1E3A5F',
    ring: '#22D3EE',
  },
  radius: 12,
};

export default colors;
