/**
 * NursePrep BD - Database Seeder
 * 
 * Usage: node scripts/seed.js
 * 
 * Requires SUPABASE_SERVICE_KEY env var from Supabase Dashboard → Settings → API
 */

const { createClient } = require('@supabase/supabase-js');

const SUPABASE_URL = 'https://kdlqsxxzozjjaflwoylp.supabase.co';
const SERVICE_KEY = process.env.SUPABASE_SERVICE_KEY;

if (!SERVICE_KEY) {
  console.error('❌ Set SUPABASE_SERVICE_KEY environment variable');
  console.error('   Get it from: Supabase Dashboard → Settings → API → service_role key');
  process.exit(1);
}

const supabase = createClient(SUPABASE_URL, SERVICE_KEY);
const BATCH = 100;

const questions = [
  // ─── NURSING (500 questions) ──────────────────────────────────
  { category:'Nursing', subject:'Fundamentals of Nursing', chapter:'Nursing Process', question:'What is the first step of the nursing process?', option_a:'Planning', option_b:'Assessment', option_c:'Implementation', option_d:'Evaluation', correct_answer:'b', explanation:'Assessment is the first step of the nursing process involving systematic data collection.', memory_tip:'ADPIE - Assessment first', difficulty:'easy', importance:5, tags:['nursing-process'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Fundamentals of Nursing', chapter:'Vital Signs', question:'What is the normal body temperature range in Celsius?', option_a:'35-36°C', option_b:'36-37.5°C', option_c:'37.5-38.5°C', option_d:'38.5-39.5°C', correct_answer:'b', explanation:'Normal body temperature is 36-37.5°C. Fever >37.5°C.', memory_tip:'36-37.5 is alive and well', difficulty:'easy', importance:5, tags:['vital-signs'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Fundamentals of Nursing', chapter:'Vital Signs', question:'What is the normal adult pulse rate?', option_a:'40-60 bpm', option_b:'60-100 bpm', option_c:'100-120 bpm', option_d:'120-140 bpm', correct_answer:'b', explanation:'Normal adult resting heart rate is 60-100 beats per minute.', memory_tip:'60-100 is normal', difficulty:'easy', importance:5, tags:['vital-signs'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Fundamentals of Nursing', chapter:'Vital Signs', question:'What is the normal adult respiratory rate?', option_a:'8-12 breaths/min', option_b:'12-20 breaths/min', option_c:'20-30 breaths/min', option_d:'30-40 breaths/min', correct_answer:'b', explanation:'Normal adult respiratory rate is 12-20 breaths per minute.', memory_tip:'12 to 20, breathing is plenty', difficulty:'easy', importance:5, tags:['vital-signs'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Fundamentals of Nursing', chapter:'Vital Signs', question:'What is the normal adult blood pressure range?', option_a:'90/60-120/80 mmHg', option_b:'120/80-140/90 mmHg', option_c:'140/90-160/100 mmHg', option_d:'80/60-100/70 mmHg', correct_answer:'a', explanation:'Normal adult BP is 90/60 to 120/80 mmHg.', memory_tip:'120/80 is perfect', difficulty:'easy', importance:5, tags:['vital-signs'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Fundamentals of Nursing', chapter:'Injection Techniques', question:'What is the correct angle for intramuscular (IM) injection?', option_a:'15 degrees', option_b:'45 degrees', option_c:'90 degrees', option_d:'30 degrees', correct_answer:'c', explanation:'IM injections are given at a 90-degree angle.', memory_tip:'IM = 90° straight in', difficulty:'easy', importance:4, tags:['injections'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Fundamentals of Nursing', chapter:'Injection Techniques', question:'What is the correct angle for subcutaneous injection?', option_a:'15 degrees', option_b:'45 degrees', option_c:'90 degrees', option_d:'60 degrees', correct_answer:'b', explanation:'Subcutaneous injections are given at a 45-degree angle.', memory_tip:'SC = 45° angle', difficulty:'easy', importance:4, tags:['injections'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Fundamentals of Nursing', chapter:'Injection Techniques', question:'What is the correct angle for intradermal injection?', option_a:'5-15 degrees', option_b:'45 degrees', option_c:'90 degrees', option_d:'30 degrees', correct_answer:'a', explanation:'Intradermal injections are given at a 5-15 degree angle.', memory_tip:'ID = 5-15° just under skin', difficulty:'medium', importance:4, tags:['injections'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Fundamentals of Nursing', chapter:'Wound Care', question:'Which type of wound healing occurs with surgical incisions?', option_a:'Primary intention', option_b:'Secondary intention', option_c:'Tertiary intention', option_d:'Delayed primary', correct_answer:'a', explanation:'Primary intention healing occurs when wound edges are approximated.', memory_tip:'Primary = edges together', difficulty:'medium', importance:4, tags:['wound-care'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Fundamentals of Nursing', chapter:'Wound Care', question:'Which type of wound drainage is clear and watery?', option_a:'Serous', option_b:'Sanguineous', option_c:'Serosanguineous', option_d:'Purulent', correct_answer:'a', explanation:'Serous drainage is clear, watery plasma.', memory_tip:'Serous = clear like water', difficulty:'medium', importance:4, tags:['wound-care'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Medical Surgical Nursing', chapter:'Cardiovascular', question:'What is the most common symptom of myocardial infarction?', option_a:'Epigastric pain', option_b:'Chest pain radiating to left arm', option_c:'Back pain', option_d:'Jaw pain', correct_answer:'b', explanation:'Classic MI is substernal chest pain radiating to left arm.', memory_tip:'MI = chest pain + left arm', difficulty:'easy', importance:5, tags:['cardiac'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Medical Surgical Nursing', chapter:'Cardiovascular', question:'Which type of shock has warm, flushed skin?', option_a:'Hypovolemic', option_b:'Cardiogenic', option_c:'Septic shock (early)', option_d:'Neurogenic', correct_answer:'c', explanation:'Early septic shock presents with warm, flushed skin due to vasodilation.', memory_tip:'Warm = early sepsis', difficulty:'hard', importance:5, tags:['shock'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Medical Surgical Nursing', chapter:'Cardiovascular', question:'What is the first sign of hypovolemic shock?', option_a:'Bradycardia', option_b:'Increased BP', option_c:'Tachycardia', option_d:'Decreased urine', correct_answer:'c', explanation:'Tachycardia is an early compensatory mechanism.', memory_tip:'Heart races first when volume drops', difficulty:'medium', importance:5, tags:['shock'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Medical Surgical Nursing', chapter:'Cardiovascular', question:'Which medication reverses opioid overdose?', option_a:'Flumazenil', option_b:'Naloxone', option_c:'Atropine', option_d:'Epinephrine', correct_answer:'b', explanation:'Naloxone is a pure opioid antagonist.', memory_tip:'Naloxone = NO opioids', difficulty:'easy', importance:5, tags:['emergency'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Medical Surgical Nursing', chapter:'Cardiovascular', question:'Normal range of serum potassium?', option_a:'3.5-5.0 mEq/L', option_b:'5.0-6.5 mEq/L', option_c:'2.0-3.5 mEq/L', option_d:'6.5-8.0 mEq/L', correct_answer:'a', explanation:'Normal potassium is 3.5-5.0 mEq/L.', memory_tip:'3.5 to 5.0 keeps heart alive', difficulty:'easy', importance:5, tags:['electrolytes'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Medical Surgical Nursing', chapter:'Cardiovascular', question:'Which electrolyte imbalance causes peaked T waves?', option_a:'Hypokalemia', option_b:'Hyperkalemia', option_c:'Hypocalcemia', option_d:'Hypercalcemia', correct_answer:'b', explanation:'Hyperkalemia causes peaked T waves on ECG.', memory_tip:'High K+ = Tall T waves', difficulty:'hard', importance:5, tags:['ecg'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Medical Surgical Nursing', chapter:'Cardiovascular', question:'Normal range of serum sodium?', option_a:'115-125 mEq/L', option_b:'125-135 mEq/L', option_c:'135-145 mEq/L', option_d:'145-155 mEq/L', correct_answer:'c', explanation:'Normal sodium is 135-145 mEq/L.', memory_tip:'135-145, sodium keeps us alive', difficulty:'easy', importance:5, tags:['electrolytes'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Medical Surgical Nursing', chapter:'Cardiovascular', question:'Normal range of serum calcium?', option_a:'6.5-8.5 mg/dL', option_b:'8.5-10.5 mg/dL', option_c:'10.5-12.5 mg/dL', option_d:'12.5-14.5 mg/dL', correct_answer:'b', explanation:'Normal calcium is 8.5-10.5 mg/dL.', memory_tip:'8.5-10.5 calcium keeps muscles alive', difficulty:'easy', importance:4, tags:['electrolytes'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Medical Surgical Nursing', chapter:'Respiratory', question:'Best position for a patient with dyspnea?', option_a:'Supine', option_b:'Fowler\'s', option_c:'Prone', option_d:'Lithotomy', correct_answer:'b', explanation:'Fowler\'s position facilitates breathing.', memory_tip:'Fowler = breathing easier', difficulty:'easy', importance:4, tags:['positioning'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Medical Surgical Nursing', chapter:'Respiratory', question:'Most common cause of community-acquired pneumonia?', option_a:'H. influenzae', option_b:'M. pneumoniae', option_c:'S. pneumoniae', option_d:'C. pneumoniae', correct_answer:'c', explanation:'S. pneumoniae is the most common cause.', memory_tip:'S. pneumo = #1 pneumonia', difficulty:'medium', importance:4, tags:['respiratory'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Medical Surgical Nursing', chapter:'Respiratory', question:'Most common symptom of pulmonary embolism?', option_a:'Hemoptysis', option_b:'Dyspnea', option_c:'Chest pain', option_d:'Cough', correct_answer:'b', explanation:'Sudden dyspnea is the most common symptom of PE.', memory_tip:'PE = sudden shortness of breath', difficulty:'medium', importance:5, tags:['respiratory'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Medical Surgical Nursing', chapter:'Respiratory', question:'Isolation required for tuberculosis?', option_a:'Contact', option_b:'Droplet', option_c:'Airborne', option_d:'Standard', correct_answer:'c', explanation:'TB requires airborne isolation with N95 respirator.', memory_tip:'TB = Airborne', difficulty:'medium', importance:5, tags:['infection-control'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Medical Surgical Nursing', chapter:'Gastrointestinal', question:'Most common cause of acute pancreatitis?', option_a:'Hyperlipidemia', option_b:'Alcohol consumption', option_c:'Trauma', option_d:'Infection', correct_answer:'b', explanation:'Alcohol and gallstones are the most common causes.', memory_tip:'Alcohol + Gallstones = Pancreatitis', difficulty:'medium', importance:4, tags:['GI'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Medical Surgical Nursing', chapter:'Gastrointestinal', question:'Most common symptom of GERD?', option_a:'Dysphagia', option_b:'Heartburn', option_c:'Regurgitation', option_d:'Chest pain', correct_answer:'b', explanation:'Heartburn is the most common symptom of GERD.', memory_tip:'GERD = burning heartburn', difficulty:'easy', importance:4, tags:['GI'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Medical Surgical Nursing', chapter:'Gastrointestinal', question:'Most common complication of peptic ulcer disease?', option_a:'Perforation', option_b:'Hemorrhage', option_c:'Gastric outlet obstruction', option_d:'Penetration', correct_answer:'b', explanation:'Hemorrhage occurs in 15-20% of PUD patients.', memory_tip:'PUD = bleeding is #1', difficulty:'medium', importance:4, tags:['GI'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Medical Surgical Nursing', chapter:'Neurology', question:'Glasgow Coma Scale range?', option_a:'1-10', option_b:'3-15', option_c:'5-20', option_d:'0-15', correct_answer:'b', explanation:'GCS ranges from 3 (deep coma) to 15 (fully awake).', memory_tip:'GCS 3-15', difficulty:'easy', importance:5, tags:['neurology'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Medical Surgical Nursing', chapter:'Neurology', question:'Most common type of stroke?', option_a:'Hemorrhagic', option_b:'Ischemic', option_c:'Embolic', option_d:'Thrombotic', correct_answer:'b', explanation:'Ischemic stroke accounts for 87% of all strokes.', memory_tip:'87% of strokes are ischemic', difficulty:'easy', importance:5, tags:['neurology'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Medical Surgical Nursing', chapter:'Neurology', question:'Assessment finding indicating increased ICP?', option_a:'Pinpoint pupils', option_b:'Bradycardia', option_c:'Cushing\'s triad', option_d:'Hypotension', correct_answer:'c', explanation:'Cushing\'s triad = HTN, bradycardia, irregular respirations.', memory_tip:'Cushing = HTN + brady + irregular breathing', difficulty:'hard', importance:5, tags:['neurology'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Medical Surgical Nursing', chapter:'Endocrine', question:'Normal range of fasting blood glucose?', option_a:'3.9-6.1 mmol/L', option_b:'6.1-7.0 mmol/L', option_c:'7.0-11.1 mmol/L', option_d:'2.5-3.9 mmol/L', correct_answer:'a', explanation:'Normal fasting glucose is 3.9-6.1 mmol/L.', memory_tip:'3.9-6.1 = normal', difficulty:'easy', importance:5, tags:['endocrine'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Medical Surgical Nursing', chapter:'Endocrine', question:'Most common cause of hyperthyroidism?', option_a:'Thyroiditis', option_b:'Graves\' disease', option_c:'Toxic nodular goiter', option_d:'Pituitary adenoma', correct_answer:'b', explanation:'Graves\' disease is the most common cause.', memory_tip:'Graves = most common hyperthyroid', difficulty:'medium', importance:4, tags:['endocrine'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Medical Surgical Nursing', chapter:'Endocrine', question:'Most common cause of hypothyroidism?', option_a:'Pituitary tumor', option_b:'Hashimoto\'s thyroiditis', option_c:'Iodine deficiency', option_d:'Thyroidectomy', correct_answer:'b', explanation:'Hashimoto\'s thyroiditis is most common.', memory_tip:'Hashimoto = most common hypothyroid', difficulty:'medium', importance:4, tags:['endocrine'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Medical Surgical Nursing', chapter:'Renal', question:'Normal range of serum creatinine?', option_a:'0.2-0.6 mg/dL', option_b:'0.6-1.2 mg/dL', option_c:'1.2-2.0 mg/dL', option_d:'2.0-3.0 mg/dL', correct_answer:'b', explanation:'Normal creatinine is 0.6-1.2 mg/dL.', memory_tip:'Creatinine 0.6-1.2 = kidneys working', difficulty:'easy', importance:5, tags:['renal'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Medical Surgical Nursing', chapter:'Renal', question:'Most common cause of end-stage renal disease?', option_a:'Glomerulonephritis', option_b:'Hypertension', option_c:'Diabetes mellitus', option_d:'Polycystic kidney disease', correct_answer:'c', explanation:'Diabetes is the leading cause of ESRD.', memory_tip:'Diabetes = #1 kidney failure', difficulty:'medium', importance:5, tags:['renal'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Medical Surgical Nursing', chapter:'Renal', question:'Most common symptom of UTI?', option_a:'Fever', option_b:'Dysuria', option_c:'Hematuria', option_d:'Flank pain', correct_answer:'b', explanation:'Dysuria is the most common UTI symptom.', memory_tip:'UTI = burning when you pee', difficulty:'easy', importance:4, tags:['renal'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Medical Surgical Nursing', chapter:'Hematology', question:'Normal hemoglobin in adult males?', option_a:'10-12 g/dL', option_b:'12-14 g/dL', option_c:'13.5-17.5 g/dL', option_d:'15-20 g/dL', correct_answer:'c', explanation:'Normal Hb for males is 13.5-17.5 g/dL.', memory_tip:'Male Hb 13.5-17.5', difficulty:'easy', importance:4, tags:['hematology'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Medical Surgical Nursing', chapter:'Hematology', question:'Normal WBC count?', option_a:'2,000-5,000/mm³', option_b:'4,000-11,000/mm³', option_c:'11,000-15,000/mm³', option_d:'15,000-20,000/mm³', correct_answer:'b', explanation:'Normal WBC is 4,000-11,000/mm³.', memory_tip:'WBC 4-11', difficulty:'easy', importance:4, tags:['hematology'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Medical Surgical Nursing', chapter:'Hematology', question:'Normal platelet count?', option_a:'50,000-150,000/mm³', option_b:'150,000-450,000/mm³', option_c:'450,000-750,000/mm³', option_d:'750,000-1,000,000/mm³', correct_answer:'b', explanation:'Normal platelets are 150,000-450,000/mm³.', memory_tip:'Platelets 150-450', difficulty:'easy', importance:4, tags:['hematology'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Medical Surgical Nursing', chapter:'Infection Control', question:'Most common nosocomial infection?', option_a:'Surgical site', option_b:'UTI', option_c:'Pneumonia', option_d:'Bloodstream', correct_answer:'b', explanation:'UTI is the most common healthcare-associated infection.', memory_tip:'Hospital UTI = #1', difficulty:'medium', importance:4, tags:['infection-control'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Medical Surgical Nursing', chapter:'Infection Control', question:'Isolation needed for C. difficile?', option_a:'Airborne', option_b:'Droplet', option_c:'Contact', option_d:'Standard', correct_answer:'c', explanation:'C. diff requires contact isolation.', memory_tip:'C. diff = Contact', difficulty:'medium', importance:4, tags:['infection-control'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Medical Surgical Nursing', chapter:'Infection Control', question:'Isolation needed for MRSA?', option_a:'Airborne', option_b:'Droplet', option_c:'Contact', option_d:'Standard', correct_answer:'c', explanation:'MRSA requires contact isolation.', memory_tip:'MRSA = Contact', difficulty:'medium', importance:4, tags:['infection-control'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Pharmacology', chapter:'Cardiovascular Drugs', question:'First-line treatment for hypertension?', option_a:'Metoprolol', option_b:'HCTZ', option_c:'Lisinopril', option_d:'Amlodipine', correct_answer:'c', explanation:'ACE inhibitors are first-line for hypertension.', memory_tip:'ACE inhibitors = first line', difficulty:'medium', importance:5, tags:['pharmacology'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Pharmacology', chapter:'Cardiovascular Drugs', question:'Antidote for heparin overdose?', option_a:'Vitamin K', option_b:'Protamine sulfate', option_c:'Naloxone', option_d:'Flumazenil', correct_answer:'b', explanation:'Protamine sulfate neutralizes heparin.', memory_tip:'Protamine = heparin antidote', difficulty:'medium', importance:4, tags:['pharmacology'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Pharmacology', chapter:'Cardiovascular Drugs', question:'Antidote for warfarin overdose?', option_a:'Protamine sulfate', option_b:'Vitamin K', option_c:'Naloxone', option_d:'Flumazenil', correct_answer:'b', explanation:'Vitamin K reverses warfarin.', memory_tip:'Vitamin K = warfarin antidote', difficulty:'medium', importance:4, tags:['pharmacology'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Pharmacology', chapter:'Cardiovascular Drugs', question:'Which is a beta-blocker?', option_a:'Lisinopril', option_b:'Metoprolol', option_c:'Amlodipine', option_d:'HCTZ', correct_answer:'b', explanation:'Metoprolol is a beta-1 selective blocker.', memory_tip:'-olol = beta blockers', difficulty:'easy', importance:4, tags:['pharmacology'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Pharmacology', chapter:'Cardiovascular Drugs', question:'Which is a calcium channel blocker?', option_a:'Metoprolol', option_b:'Amlodipine', option_c:'Lisinopril', option_d:'Losartan', correct_answer:'b', explanation:'Amlodipine is a calcium channel blocker.', memory_tip:'-dipine = CCBs', difficulty:'easy', importance:4, tags:['pharmacology'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Pharmacology', chapter:'Endocrine Drugs', question:'Mechanism of action of metformin?', option_a:'Increases insulin secretion', option_b:'Decreases hepatic glucose production', option_c:'Blocks glucose absorption', option_d:'Increases insulin sensitivity', correct_answer:'b', explanation:'Metformin decreases hepatic glucose production.', memory_tip:'Metformin = liver makes less sugar', difficulty:'medium', importance:5, tags:['pharmacology'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Pharmacology', chapter:'Endocrine Drugs', question:'First-line treatment for type 2 diabetes?', option_a:'Insulin', option_b:'Metformin', option_c:'Glipizide', option_d:'Pioglitazone', correct_answer:'b', explanation:'Metformin is first-line for type 2 diabetes.', memory_tip:'Metformin = #1 for type 2', difficulty:'easy', importance:5, tags:['pharmacology'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Pharmacology', chapter:'Emergency Drugs', question:'First-line treatment for anaphylaxis?', option_a:'Diphenhydramine', option_b:'Epinephrine', option_c:'Methylprednisolone', option_d:'Albuterol', correct_answer:'b', explanation:'Epinephrine IM is first-line for anaphylaxis.', memory_tip:'Epi first for anaphylaxis', difficulty:'easy', importance:5, tags:['pharmacology'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Pharmacology', chapter:'Emergency Drugs', question:'Antidote for benzodiazepine overdose?', option_a:'Naloxone', option_b:'Flumazenil', option_c:'Atropine', option_d:'Protamine', correct_answer:'b', explanation:'Flumazenil is a benzodiazepine antagonist.', memory_tip:'Flumazenil = benzo antidote', difficulty:'medium', importance:4, tags:['pharmacology'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Pharmacology', chapter:'Emergency Drugs', question:'Antidote for acetaminophen overdose?', option_a:'Naloxone', option_b:'N-acetylcysteine', option_c:'Flumazenil', option_d:'Vitamin K', correct_answer:'b', explanation:'NAC replenishes glutathione stores.', memory_tip:'NAC = Tylenol antidote', difficulty:'medium', importance:4, tags:['pharmacology'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Pharmacology', chapter:'Antibiotics', question:'Antibiotic contraindicated in children under 8?', option_a:'Penicillin', option_b:'Tetracycline', option_c:'Amoxicillin', option_d:'Cephalexin', correct_answer:'b', explanation:'Tetracyclines cause tooth discoloration in children.', memory_tip:'Tetracycline = no for kids under 8', difficulty:'medium', importance:4, tags:['pharmacology'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Pharmacology', chapter:'Antibiotics', question:'Which drug requires monitoring for ototoxicity?', option_a:'Penicillin', option_b:'Gentamicin', option_c:'Ciprofloxacin', option_d:'Doxycycline', correct_answer:'b', explanation:'Aminoglycosides cause ototoxicity and nephrotoxicity.', memory_tip:'Gentamicin = ear + kidney damage', difficulty:'medium', importance:4, tags:['pharmacology'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Anatomy', chapter:'General Anatomy', question:'Largest organ of the human body?', option_a:'Liver', option_b:'Brain', option_c:'Skin', option_d:'Heart', correct_answer:'c', explanation:'The skin is the largest organ.', memory_tip:'Skin = largest organ', difficulty:'easy', importance:3, tags:['anatomy'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Anatomy', chapter:'General Anatomy', question:'How many bones in adult human body?', option_a:'200', option_b:'206', option_c:'212', option_d:'218', correct_answer:'b', explanation:'The adult skeleton has 206 bones.', memory_tip:'206 bones', difficulty:'easy', importance:3, tags:['anatomy'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Anatomy', chapter:'Cardiovascular Anatomy', question:'Which chamber pumps blood to the body?', option_a:'Right atrium', option_b:'Right ventricle', option_c:'Left atrium', option_d:'Left ventricle', correct_answer:'d', explanation:'The left ventricle pumps to the entire body.', memory_tip:'Left ventricle = pumps to whole body', difficulty:'easy', importance:4, tags:['anatomy'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Anatomy', chapter:'Cardiovascular Anatomy', question:'Largest artery in the body?', option_a:'Pulmonary', option_b:'Carotid', option_c:'Aorta', option_d:'Femoral', correct_answer:'c', explanation:'The aorta is the largest artery.', memory_tip:'Aorta = king of arteries', difficulty:'easy', importance:3, tags:['anatomy'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Anatomy', chapter:'Cardiovascular Anatomy', question:'Valve between left atrium and left ventricle?', option_a:'Tricuspid', option_b:'Pulmonary', option_c:'Mitral', option_d:'Aortic', correct_answer:'c', explanation:'The mitral valve separates left atrium and ventricle.', memory_tip:'Mitral = left side', difficulty:'medium', importance:4, tags:['anatomy'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Anatomy', chapter:'Neurological Anatomy', question:'Part of brain controlling balance?', option_a:'Cerebrum', option_b:'Cerebellum', option_c:'Brainstem', option_d:'Hypothalamus', correct_answer:'b', explanation:'The cerebellum coordinates balance and movement.', memory_tip:'Cerebellum = coordination', difficulty:'easy', importance:3, tags:['anatomy'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Anatomy', chapter:'Neurological Anatomy', question:'Cranial nerve responsible for vision?', option_a:'CN I', option_b:'CN II', option_c:'CN III', option_d:'CN IV', correct_answer:'b', explanation:'CN II (Optic) is responsible for vision.', memory_tip:'CN II = 2 eyes = Optic', difficulty:'easy', importance:4, tags:['anatomy'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Anatomy', chapter:'Neurological Anatomy', question:'Cranial nerve responsible for hearing?', option_a:'CN VII', option_b:'CN VIII', option_c:'CN IX', option_d:'CN X', correct_answer:'b', explanation:'CN VIII (Vestibulocochlear) is for hearing.', memory_tip:'CN VIII = 8 looks like ear', difficulty:'easy', importance:4, tags:['anatomy'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Anatomy', chapter:'Renal Anatomy', question:'Functional unit of the kidney?', option_a:'Nephron', option_b:'Glomerulus', option_c:'Bowman\'s capsule', option_d:'Loop of Henle', correct_answer:'a', explanation:'The nephron is the functional unit.', memory_tip:'Nephron = kidney unit', difficulty:'easy', importance:4, tags:['anatomy'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Anatomy', chapter:'Respiratory Anatomy', question:'Function of alveoli?', option_a:'Filter air', option_b:'Gas exchange', option_c:'Produce mucus', option_d:'Warm air', correct_answer:'b', explanation:'Alveoli are for gas exchange.', memory_tip:'Alveoli = gas exchange', difficulty:'easy', importance:4, tags:['anatomy'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Anatomy', chapter:'Respiratory Anatomy', question:'How many lobes does the right lung have?', option_a:'2', option_b:'3', option_c:'4', option_d:'5', correct_answer:'b', explanation:'Right lung has 3 lobes, left has 2.', memory_tip:'Right = 3 lobes', difficulty:'easy', importance:3, tags:['anatomy'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Pediatric Nursing', chapter:'Newborn Care', question:'Normal heart rate for a newborn?', option_a:'60-100 bpm', option_b:'100-160 bpm', option_c:'120-180 bpm', option_d:'80-120 bpm', correct_answer:'b', explanation:'Newborn HR is 100-160 bpm.', memory_tip:'Newborn HR 100-160', difficulty:'easy', importance:4, tags:['pediatric'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Pediatric Nursing', chapter:'Newborn Care', question:'Which vaccine is given at birth?', option_a:'MMR', option_b:'BCG', option_c:'DPT', option_d:'Polio', correct_answer:'b', explanation:'BCG is given at birth for TB prevention.', memory_tip:'BCG = birth vaccine', difficulty:'easy', importance:4, tags:['pediatric'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Pediatric Nursing', chapter:'Newborn Care', question:'Normal birth weight of full-term newborn?', option_a:'2.0-2.5 kg', option_b:'2.5-4.0 kg', option_c:'4.0-4.5 kg', option_d:'4.5-5.0 kg', correct_answer:'b', explanation:'Normal birth weight is 2.5-4.0 kg.', memory_tip:'2.5-4.0 kg = healthy baby', difficulty:'easy', importance:4, tags:['pediatric'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Pediatric Nursing', chapter:'Newborn Care', question:'Vitamin given prophylactically to newborns?', option_a:'Vitamin A', option_b:'Vitamin B', option_c:'Vitamin C', option_d:'Vitamin K', correct_answer:'d', explanation:'Vitamin K prevents hemorrhagic disease.', memory_tip:'Vitamin K = prevents bleeding', difficulty:'medium', importance:4, tags:['pediatric'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Pediatric Nursing', chapter:'Growth and Development', question:'When does anterior fontanelle close?', option_a:'6-8 months', option_b:'9-12 months', option_c:'12-18 months', option_d:'18-24 months', correct_answer:'c', explanation:'Anterior fontanelle closes at 12-18 months.', memory_tip:'Closes at 12-18 months', difficulty:'medium', importance:4, tags:['pediatric'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Pediatric Nursing', chapter:'Growth and Development', question:'When do children start walking independently?', option_a:'6-9 months', option_b:'9-12 months', option_c:'12-15 months', option_d:'15-18 months', correct_answer:'c', explanation:'Most walk between 12-15 months.', memory_tip:'Walking = around 1st birthday', difficulty:'easy', importance:3, tags:['pediatric'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Pediatric Nursing', chapter:'Growth and Development', question:'Most common cause of fever in children?', option_a:'Bacterial', option_b:'Viral', option_c:'Fungal', option_d:'Parasitic', correct_answer:'b', explanation:'Viral infections are most common.', memory_tip:'Kids + fever = virus', difficulty:'easy', importance:3, tags:['pediatric'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Pediatric Nursing', chapter:'Growth and Development', question:'Most common cause of diarrhea in children?', option_a:'Bacteria', option_b:'Rotavirus', option_c:'Parasites', option_d:'Food allergy', correct_answer:'b', explanation:'Rotavirus is the most common cause.', memory_tip:'Rotavirus = #1 kids diarrhea', difficulty:'easy', importance:4, tags:['pediatric'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Pediatric Nursing', chapter:'Growth and Development', question:'Most common cancer in children?', option_a:'Brain tumor', option_b:'Leukemia', option_c:'Neuroblastoma', option_d:'Wilms tumor', correct_answer:'b', explanation:'ALL is the most common childhood cancer.', memory_tip:'ALL = most common childhood cancer', difficulty:'medium', importance:3, tags:['pediatric'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Pediatric Nursing', chapter:'Immunization', question:'Immunization given at 6 weeks?', option_a:'MMR', option_b:'Pentavalent', option_c:'BCG', option_d:'Typhoid', correct_answer:'b', explanation:'Pentavalent is given at 6, 10, 14 weeks.', memory_tip:'Pentavalent = 5 in 1 at 6 weeks', difficulty:'easy', importance:4, tags:['pediatric'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Pediatric Nursing', chapter:'Immunization', question:'Vaccine given at 9 months in Bangladesh?', option_a:'Measles', option_b:'MMR', option_c:'DPT booster', option_d:'Polio', correct_answer:'a', explanation:'Measles vaccine at 9 months in EPI.', memory_tip:'Measles at 9 months in BD', difficulty:'medium', importance:4, tags:['pediatric'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Community Nursing', chapter:'Public Health', question:'Goal of primary health care?', option_a:'Treat all diseases', option_b:'Health for all', option_c:'Build hospitals', option_d:'Train doctors', correct_answer:'b', explanation:'PHC aims for "Health for All".', memory_tip:'PHC = Health for All', difficulty:'easy', importance:4, tags:['community'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Community Nursing', chapter:'Public Health', question:'Disease targeted for eradication by WHO?', option_a:'TB', option_b:'Polio', option_c:'Malaria', option_d:'HIV', correct_answer:'b', explanation:'Polio is targeted for global eradication.', memory_tip:'Polio = next to be eradicated', difficulty:'easy', importance:4, tags:['community'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Community Nursing', chapter:'Public Health', question:'Recommended duration of exclusive breastfeeding?', option_a:'4 months', option_b:'6 months', option_c:'8 months', option_d:'12 months', correct_answer:'b', explanation:'WHO recommends 6 months exclusive breastfeeding.', memory_tip:'6 months exclusive', difficulty:'easy', importance:4, tags:['community'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Community Nursing', chapter:'Public Health', question:'Main vector for dengue fever?', option_a:'Anopheles', option_b:'Aedes', option_c:'Culex', option_d:'Sandfly', correct_answer:'b', explanation:'Aedes aegypti is the dengue vector.', memory_tip:'Aedes = dengue mosquito', difficulty:'easy', importance:4, tags:['community'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Community Nursing', chapter:'Public Health', question:'Normal BMI range?', option_a:'15-18.5', option_b:'18.5-24.9', option_c:'25-29.9', option_d:'30-34.9', correct_answer:'b', explanation:'Normal BMI is 18.5-24.9.', memory_tip:'18.5-24.9 = healthy', difficulty:'easy', importance:3, tags:['community'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Community Nursing', chapter:'Maternal Health', question:'Most common cause of maternal mortality in Bangladesh?', option_a:'Hemorrhage', option_b:'Eclampsia', option_c:'Sepsis', option_d:'Abortion', correct_answer:'a', explanation:'PPH is the leading cause in Bangladesh.', memory_tip:'PPH = #1 maternal killer in BD', difficulty:'medium', importance:5, tags:['community'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Community Nursing', chapter:'Maternal Health', question:'Vaccine given to pregnant women?', option_a:'MMR', option_b:'Tetanus toxoid', option_c:'BCG', option_d:'Hep B', correct_answer:'b', explanation:'TT prevents neonatal tetanus.', memory_tip:'TT for pregnant women', difficulty:'easy', importance:4, tags:['community'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Community Nursing', chapter:'Maternal Health', question:'Recommended number of ANC visits?', option_a:'2', option_b:'4', option_c:'6', option_d:'8', correct_answer:'b', explanation:'WHO recommends at least 4 ANC visits.', memory_tip:'4 ANC visits', difficulty:'easy', importance:4, tags:['community'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Community Nursing', chapter:'Epidemiology', question:'Vitamin deficiency causing night blindness?', option_a:'Vitamin A', option_b:'Vitamin B', option_c:'Vitamin C', option_d:'Vitamin D', correct_answer:'a', explanation:'Vitamin A deficiency causes night blindness.', memory_tip:'Vitamin A = night vision', difficulty:'easy', importance:4, tags:['community'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Community Nursing', chapter:'Epidemiology', question:'Micronutrient deficiency causing goiter?', option_a:'Iron', option_b:'Iodine', option_c:'Zinc', option_d:'Calcium', correct_answer:'b', explanation:'Iodine deficiency causes goiter.', memory_tip:'Iodine = prevents goiter', difficulty:'easy', importance:4, tags:['community'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Community Nursing', chapter:'Epidemiology', question:'Most common malnutrition in Bangladesh?', option_a:'Obesity', option_b:'Stunting', option_c:'Wasting', option_d:'Underweight', correct_answer:'b', explanation:'Stunting is most common in Bangladesh.', memory_tip:'Stunting = chronic malnutrition in BD', difficulty:'medium', importance:4, tags:['community'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Obstetrics', chapter:'Pregnancy', question:'Normal duration of pregnancy?', option_a:'36 weeks', option_b:'38 weeks', option_c:'40 weeks', option_d:'42 weeks', correct_answer:'c', explanation:'Normal pregnancy is 40 weeks.', memory_tip:'40 weeks = full term', difficulty:'easy', importance:4, tags:['obstetrics'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Obstetrics', chapter:'Pregnancy', question:'Hormone maintaining pregnancy?', option_a:'Estrogen', option_b:'Progesterone', option_c:'hCG', option_d:'Oxytocin', correct_answer:'b', explanation:'Progesterone maintains the uterine lining.', memory_tip:'Progesterone = pregnancy protector', difficulty:'medium', importance:4, tags:['obstetrics'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Obstetrics', chapter:'Pregnancy', question:'Normal fetal heart rate?', option_a:'80-100 bpm', option_b:'100-120 bpm', option_c:'120-160 bpm', option_d:'160-180 bpm', correct_answer:'c', explanation:'Fetal HR is 120-160 bpm.', memory_tip:'Fetal HR 120-160', difficulty:'easy', importance:4, tags:['obstetrics'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Obstetrics', chapter:'Pregnancy', question:'Vitamin preventing neural tube defects?', option_a:'Vitamin A', option_b:'Folic acid', option_c:'Vitamin C', option_d:'Vitamin D', correct_answer:'b', explanation:'Folic acid prevents neural tube defects.', memory_tip:'Folic acid = prevents spina bifida', difficulty:'easy', importance:5, tags:['obstetrics'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Obstetrics', chapter:'Labor and Delivery', question:'Most common cause of postpartum hemorrhage?', option_a:'Uterine atony', option_b:'Vaginal tear', option_c:'Retained placenta', option_d:'Coagulopathy', correct_answer:'a', explanation:'Uterine atony is the most common cause.', memory_tip:'Uterine atony = #1 PPH', difficulty:'medium', importance:5, tags:['obstetrics'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Obstetrics', chapter:'Labor and Delivery', question:'Stage of labor ending with complete dilation?', option_a:'First stage', option_b:'Second stage', option_c:'Third stage', option_d:'Fourth stage', correct_answer:'a', explanation:'First stage ends with complete dilation.', memory_tip:'Stage 1 = dilation', difficulty:'easy', importance:4, tags:['obstetrics'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Obstetrics', chapter:'Labor and Delivery', question:'Most common fetal presentation?', option_a:'Breech', option_b:'Vertex', option_c:'Transverse', option_d:'Face', correct_answer:'b', explanation:'Vertex (head-down) is 95% of presentations.', memory_tip:'95% = head down', difficulty:'easy', importance:4, tags:['obstetrics'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Obstetrics', chapter:'Labor and Delivery', question:'Definition of preeclampsia?', option_a:'BP>140/90 + protein after 20 weeks', option_b:'BP>160/100 alone', option_c:'BP>140/90 before 20 weeks', option_d:'BP>180/110 + seizures', correct_answer:'a', explanation:'Preeclampsia = HTN + proteinuria after 20 weeks.', memory_tip:'HTN + protein after 20 weeks', difficulty:'medium', importance:5, tags:['obstetrics'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Obstetrics', chapter:'Contraception', question:'Contraceptive providing STI protection?', option_a:'OCP', option_b:'IUD', option_c:'Male condom', option_d:'Implant', correct_answer:'c', explanation:'Condoms are the only STI-protective method.', memory_tip:'Condoms = only STI protection', difficulty:'easy', importance:3, tags:['obstetrics'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Psychiatric Nursing', chapter:'Mood Disorders', question:'Most common mental disorder worldwide?', option_a:'Schizophrenia', option_b:'Depression', option_c:'Bipolar', option_d:'Anxiety', correct_answer:'b', explanation:'Depression affects 280M+ people worldwide.', memory_tip:'Depression = most common', difficulty:'easy', importance:4, tags:['psychiatric'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Psychiatric Nursing', chapter:'Mood Disorders', question:'Neurotransmitter associated with depression?', option_a:'Dopamine', option_b:'Serotonin', option_c:'Acetylcholine', option_d:'GABA', correct_answer:'b', explanation:'Low serotonin is associated with depression.', memory_tip:'Serotonin = happy chemical', difficulty:'medium', importance:4, tags:['psychiatric'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Psychiatric Nursing', chapter:'Mood Disorders', question:'First-line treatment for depression?', option_a:'Benzodiazepines', option_b:'SSRIs', option_c:'Antipsychotics', option_d:'Mood stabilizers', correct_answer:'b', explanation:'SSRIs are first-line for depression.', memory_tip:'SSRI = first for depression', difficulty:'easy', importance:4, tags:['psychiatric'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Psychiatric Nursing', chapter:'Psychotic Disorders', question:'Most common symptom of schizophrenia?', option_a:'Depression', option_b:'Hallucinations', option_c:'Anxiety', option_d:'Insomnia', correct_answer:'b', explanation:'Auditory hallucinations are most common.', memory_tip:'Schizophrenia = hearing voices', difficulty:'easy', importance:4, tags:['psychiatric'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Psychiatric Nursing', chapter:'Psychotic Disorders', question:'Neurotransmitter associated with schizophrenia?', option_a:'Serotonin', option_b:'Dopamine', option_c:'Norepinephrine', option_d:'GABA', correct_answer:'b', explanation:'Excess dopamine contributes to schizophrenia.', memory_tip:'Dopamine = schizophrenia link', difficulty:'medium', importance:4, tags:['psychiatric'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Psychiatric Nursing', chapter:'Psychotic Disorders', question:'Which is an atypical antipsychotic?', option_a:'Haloperidol', option_b:'Risperidone', option_c:'Chlorpromazine', option_d:'Fluphenazine', correct_answer:'b', explanation:'Risperidone has fewer side effects.', memory_tip:'Risperidone = newer', difficulty:'medium', importance:4, tags:['psychiatric'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Psychiatric Nursing', chapter:'Anxiety Disorders', question:'Most common anxiety disorder?', option_a:'Panic disorder', option_b:'GAD', option_c:'Social anxiety', option_d:'Specific phobia', correct_answer:'d', explanation:'Specific phobia affects 7-9% of population.', memory_tip:'Phobias = most common anxiety', difficulty:'medium', importance:3, tags:['psychiatric'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Psychiatric Nursing', chapter:'Anxiety Disorders', question:'Most common symptom of OCD?', option_a:'Hallucinations', option_b:'Obsessions and compulsions', option_c:'Delusions', option_d:'Mood swings', correct_answer:'b', explanation:'OCD = obsessions + compulsions.', memory_tip:'OCD = obsessions + compulsions', difficulty:'easy', importance:3, tags:['psychiatric'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Psychiatric Nursing', chapter:'Substance Abuse', question:'Medication for alcohol withdrawal?', option_a:'Naloxone', option_b:'Benzodiazepines', option_c:'Disulfiram', option_d:'Naltrexone', correct_answer:'b', explanation:'Benzodiazepines prevent withdrawal seizures.', memory_tip:'Benzos = alcohol withdrawal', difficulty:'medium', importance:4, tags:['psychiatric'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Psychiatric Nursing', chapter:'Cognitive Disorders', question:'Most common cause of dementia?', option_a:'Vascular', option_b:'Lewy body', option_c:'Alzheimer\'s', option_d:'Frontotemporal', correct_answer:'c', explanation:'Alzheimer\'s accounts for 60-80% of dementia.', memory_tip:'Alzheimer = most common dementia', difficulty:'easy', importance:4, tags:['psychiatric'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Psychiatric Nursing', chapter:'Cognitive Disorders', question:'Neurotransmitter in Alzheimer\'s disease?', option_a:'Dopamine', option_b:'Serotonin', option_c:'Acetylcholine', option_d:'GABA', correct_answer:'c', explanation:'Acetylcholine deficiency in Alzheimer\'s.', memory_tip:'Acetylcholine = memory chemical', difficulty:'hard', importance:4, tags:['psychiatric'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Emergency Nursing', chapter:'Triage', question:'Priority in treating anaphylaxis?', option_a:'Call for help', option_b:'Administer epinephrine', option_c:'Start IV fluids', option_d:'Apply oxygen', correct_answer:'b', explanation:'Epinephrine is first-line for anaphylaxis.', memory_tip:'Epi first', difficulty:'easy', importance:5, tags:['emergency'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Emergency Nursing', chapter:'Triage', question:'Priority intervention for seizure?', option_a:'Restrain', option_b:'Insert airway', option_c:'Protect from injury', option_d:'Give oxygen', correct_answer:'c', explanation:'Protect from injury is priority.', memory_tip:'Seizure = protect', difficulty:'easy', importance:5, tags:['emergency'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Emergency Nursing', chapter:'Triage', question:'Shock caused by pump failure?', option_a:'Hypovolemic', option_b:'Cardiogenic', option_c:'Distributive', option_d:'Obstructive', correct_answer:'b', explanation:'Cardiogenic shock = pump failure.', memory_tip:'Cardiogenic = heart pump failure', difficulty:'easy', importance:4, tags:['emergency'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Emergency Nursing', chapter:'Burns', question:'Electrolyte imbalance in burn patients?', option_a:'Hypernatremia', option_b:'Hyperkalemia', option_c:'Hyponatremia', option_d:'Hypocalcemia', correct_answer:'b', explanation:'Cell destruction releases potassium.', memory_tip:'Burns = potassium rises', difficulty:'medium', importance:4, tags:['emergency'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Emergency Nursing', chapter:'Burns', question:'Best method to confirm NG tube placement?', option_a:'Auscultation', option_b:'pH testing', option_c:'X-ray', option_d:'Bubble test', correct_answer:'c', explanation:'X-ray is the gold standard.', memory_tip:'X-ray = gold standard', difficulty:'medium', importance:4, tags:['emergency'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Emergency Nursing', chapter:'Burns', question:'Priority intervention for chest tube?', option_a:'Clamp during transport', option_b:'Keep below chest level', option_c:'Strip tubing hourly', option_d:'Empty every shift', correct_answer:'b', explanation:'Keep drainage system below chest level.', memory_tip:'Chest tube = keep below chest', difficulty:'medium', importance:4, tags:['emergency'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Emergency Nursing', chapter:'Burns', question:'Most concerning post-op finding?', option_a:'Pain 4/10', option_b:'Temp 37.5°C', option_c:'Urine 20 mL/hr', option_d:'HR 88 bpm', correct_answer:'c', explanation:'Urine <30 mL/hr indicates hypovolemia.', memory_tip:'Urine <30 = red flag', difficulty:'medium', importance:4, tags:['emergency'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Emergency Nursing', chapter:'Burns', question:'Lab value indicating acute kidney injury?', option_a:'BUN 10', option_b:'Creatinine 2.5', option_c:'GFR 120', option_d:'BUN/Cr 10:1', correct_answer:'b', explanation:'Elevated creatinine indicates kidney injury.', memory_tip:'Creatinine up = kidney injury', difficulty:'medium', importance:5, tags:['emergency'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Emergency Nursing', chapter:'Burns', question:'Lab value indicating dehydration?', option_a:'Low BUN', option_b:'Elevated Hct', option_c:'Low Na', option_d:'Low urine SG', correct_answer:'b', explanation:'Elevated Hct indicates hemoconcentration.', memory_tip:'High Hct = dehydrated', difficulty:'medium', importance:4, tags:['emergency'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Emergency Nursing', chapter:'Burns', question:'Normal INR (not on anticoagulation)?', option_a:'0.5-1.0', option_b:'0.8-1.2', option_c:'1.5-2.5', option_d:'2.0-3.0', correct_answer:'b', explanation:'Normal INR is 0.8-1.2.', memory_tip:'INR 0.8-1.2 = normal', difficulty:'medium', importance:4, tags:['emergency'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Emergency Nursing', chapter:'Burns', question:'Normal serum bilirubin?', option_a:'0.1-0.3 mg/dL', option_b:'0.3-1.0 mg/dL', option_c:'1.0-2.0 mg/dL', option_d:'2.0-3.0 mg/dL', correct_answer:'b', explanation:'Normal bilirubin is 0.3-1.0 mg/dL.', memory_tip:'Bilirubin 0.3-1.0', difficulty:'easy', importance:3, tags:['emergency'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Emergency Nursing', chapter:'Burns', question:'Normal serum albumin?', option_a:'2.5-3.5 g/dL', option_b:'3.5-5.0 g/dL', option_c:'5.0-6.5 g/dL', option_d:'1.5-2.5 g/dL', correct_answer:'b', explanation:'Normal albumin is 3.5-5.0 g/dL.', memory_tip:'Albumin 3.5-5.0', difficulty:'medium', importance:3, tags:['emergency'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Emergency Nursing', chapter:'Burns', question:'Normal serum amylase?', option_a:'10-30 U/L', option_b:'30-110 U/L', option_c:'110-200 U/L', option_d:'200-400 U/L', correct_answer:'b', explanation:'Normal amylase is 30-110 U/L.', memory_tip:'Amylase up = pancreas problem', difficulty:'medium', importance:3, tags:['emergency'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Emergency Nursing', chapter:'Burns', question:'Normal serum lipase?', option_a:'10-50 U/L', option_b:'50-150 U/L', option_c:'150-300 U/L', option_d:'300-500 U/L', correct_answer:'b', explanation:'Normal lipase is 50-150 U/L.', memory_tip:'Lipase = specific for pancreatitis', difficulty:'medium', importance:3, tags:['emergency'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Emergency Nursing', chapter:'Burns', question:'Normal serum magnesium?', option_a:'1.3-2.1 mEq/L', option_b:'2.1-3.0 mEq/L', option_c:'3.0-4.0 mEq/L', option_d:'0.5-1.3 mEq/L', correct_answer:'a', explanation:'Normal Mg is 1.3-2.1 mEq/L.', memory_tip:'Mg 1.3-2.1', difficulty:'medium', importance:3, tags:['emergency'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Emergency Nursing', chapter:'Burns', question:'Normal serum phosphorus?', option_a:'1.5-2.5 mg/dL', option_b:'2.5-4.5 mg/dL', option_c:'4.5-6.5 mg/dL', option_d:'6.5-8.5 mg/dL', correct_answer:'b', explanation:'Normal phosphorus is 2.5-4.5 mg/dL.', memory_tip:'Phosphorus 2.5-4.5', difficulty:'medium', importance:3, tags:['emergency'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Emergency Nursing', chapter:'Burns', question:'Normal serum chloride?', option_a:'90-95 mEq/L', option_b:'95-105 mEq/L', option_c:'105-115 mEq/L', option_d:'115-125 mEq/L', correct_answer:'b', explanation:'Normal chloride is 95-105 mEq/L.', memory_tip:'Chloride 95-105', difficulty:'medium', importance:3, tags:['emergency'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Emergency Nursing', chapter:'Burns', question:'Normal TSH?', option_a:'0.1-0.4 mIU/L', option_b:'0.4-4.0 mIU/L', option_c:'4.0-10.0 mIU/L', option_d:'10.0-20.0 mIU/L', correct_answer:'b', explanation:'Normal TSH is 0.4-4.0 mIU/L.', memory_tip:'TSH 0.4-4.0', difficulty:'medium', importance:3, tags:['emergency'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Emergency Nursing', chapter:'Burns', question:'Normal PaO2?', option_a:'40-60 mmHg', option_b:'60-80 mmHg', option_c:'80-100 mmHg', option_d:'100-120 mmHg', correct_answer:'c', explanation:'Normal PaO2 is 80-100 mmHg.', memory_tip:'PaO2 80-100', difficulty:'medium', importance:4, tags:['emergency'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Emergency Nursing', chapter:'Burns', question:'Normal PaCO2?', option_a:'25-35 mmHg', option_b:'35-45 mmHg', option_c:'45-55 mmHg', option_d:'55-65 mmHg', correct_answer:'b', explanation:'Normal PaCO2 is 35-45 mmHg.', memory_tip:'PaCO2 35-45', difficulty:'medium', importance:4, tags:['emergency'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Emergency Nursing', chapter:'Burns', question:'Normal blood pH?', option_a:'7.25-7.35', option_b:'7.35-7.45', option_c:'7.45-7.55', option_d:'7.0-7.25', correct_answer:'b', explanation:'Normal pH is 7.35-7.45.', memory_tip:'pH 7.35-7.45', difficulty:'medium', importance:4, tags:['emergency'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Emergency Nursing', chapter:'Burns', question:'Respiratory alkalosis findings?', option_a:'Decreased pH, increased CO2', option_b:'Increased pH, decreased CO2', option_c:'Decreased pH, decreased HCO3', option_d:'Increased pH, increased HCO3', correct_answer:'b', explanation:'Resp alkalosis = high pH + low CO2.', memory_tip:'High pH + low CO2', difficulty:'hard', importance:4, tags:['emergency'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Emergency Nursing', chapter:'Burns', question:'Metabolic acidosis findings?', option_a:'Increased pH, increased HCO3', option_b:'Decreased pH, decreased HCO3', option_c:'Increased pH, decreased CO2', option_d:'Decreased pH, increased CO2', correct_answer:'b', explanation:'Metabolic acidosis = low pH + low HCO3.', memory_tip:'Low pH + low HCO3', difficulty:'hard', importance:4, tags:['emergency'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Emergency Nursing', chapter:'Burns', question:'Electrolyte causing U waves on ECG?', option_a:'Hyperkalemia', option_b:'Hypokalemia', option_c:'Hypercalcemia', option_d:'Hypocalcemia', correct_answer:'b', explanation:'Hypokalemia causes U waves.', memory_tip:'Low K+ = U waves', difficulty:'hard', importance:4, tags:['emergency'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Emergency Nursing', chapter:'Burns', question:'Most common cause of COPD?', option_a:'Asthma', option_b:'Smoking', option_c:'Air pollution', option_d:'Alpha-1 antitrypsin', correct_answer:'b', explanation:'Smoking causes 85-90% of COPD.', memory_tip:'Smoking = #1 COPD', difficulty:'easy', importance:4, tags:['respiratory'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Emergency Nursing', chapter:'Burns', question:'Most common cause of community UTI?', option_a:'Klebsiella', option_b:'Proteus', option_c:'E. coli', option_d:'Pseudomonas', correct_answer:'c', explanation:'E. coli causes 80-85% of UTIs.', memory_tip:'E. coli = #1 UTI', difficulty:'easy', importance:4, tags:['renal'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Emergency Nursing', chapter:'Burns', question:'Most common type of hernia?', option_a:'Femoral', option_b:'Incisional', option_c:'Inguinal', option_d:'Umbilical', correct_answer:'c', explanation:'Inguinal hernia is 75% of all hernias.', memory_tip:'Inguinal = most common', difficulty:'easy', importance:3, tags:['GI'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Emergency Nursing', chapter:'Burns', question:'Most common complication of cirrhosis?', option_a:'Encephalopathy', option_b:'Portal HTN', option_c:'Ascites', option_d:'Varices', correct_answer:'c', explanation:'Ascites is the most common complication.', memory_tip:'Cirrhosis = ascites', difficulty:'medium', importance:4, tags:['GI'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Emergency Nursing', chapter:'Burns', question:'Vaccine contraindicated in pregnancy?', option_a:'Tetanus', option_b:'Hep B', option_c:'MMR', option_d:'Influenza', correct_answer:'c', explanation:'Live vaccines like MMR are contraindicated.', memory_tip:'MMR = no during pregnancy', difficulty:'easy', importance:4, tags:['immunization'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Emergency Nursing', chapter:'Burns', question:'Isolation for chickenpox?', option_a:'Contact', option_b:'Droplet', option_c:'Airborne + contact', option_d:'Standard', correct_answer:'c', explanation:'Chickenpox requires airborne + contact.', memory_tip:'Chickenpox = airborne + contact', difficulty:'medium', importance:3, tags:['infection-control'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Emergency Nursing', chapter:'Burns', question:'Isolation for influenza?', option_a:'Airborne', option_b:'Droplet', option_c:'Contact', option_d:'Standard', correct_answer:'b', explanation:'Influenza requires droplet precautions.', memory_tip:'Flu = droplet', difficulty:'medium', importance:3, tags:['infection-control'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Emergency Nursing', chapter:'Burns', question:'Isolation for measles?', option_a:'Contact', option_b:'Droplet', option_c:'Airborne', option_d:'Standard', correct_answer:'c', explanation:'Measles requires airborne isolation.', memory_tip:'Measles = airborne', difficulty:'medium', importance:3, tags:['infection-control'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Emergency Nursing', chapter:'Burns', question:'Most common complication of measles?', option_a:'Encephalitis', option_b:'Pneumonia', option_c:'Otitis media', option_d:'Diarrhea', correct_answer:'c', explanation:'Otitis media occurs in 5-15% of cases.', memory_tip:'Measles = ear infection', difficulty:'medium', importance:3, tags:['pediatric'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Emergency Nursing', chapter:'Burns', question:'Most common complication of diabetes?', option_a:'DKA', option_b:'Cardiovascular disease', option_c:'Nephropathy', option_d:'Retinopathy', correct_answer:'b', explanation:'CVD is the leading cause of death in diabetes.', memory_tip:'Diabetes = heart disease #1', difficulty:'medium', importance:5, tags:['endocrine'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Emergency Nursing', chapter:'Burns', question:'Fracture common in elderly with osteoporosis?', option_a:'Compound', option_b:'Hip', option_c:'Greenstick', option_d:'Comminuted', correct_answer:'b', explanation:'Hip fracture is most common in elderly.', memory_tip:'Elderly + osteoporosis = hip fracture', difficulty:'easy', importance:3, tags:['orthopedic'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Emergency Nursing', chapter:'Burns', question:'Fracture common in children?', option_a:'Comminuted', option_b:'Greenstick', option_c:'Compound', option_d:'Pathologic', correct_answer:'b', explanation:'Greenstick fracture is common in children.', memory_tip:'Kids = greenstick', difficulty:'easy', importance:3, tags:['orthopedic'], language:'english', verified:true, active:true },
  { category:'Nursing', subject:'Emergency Nursing', chapter:'Burns', question:'Incontinence with coughing?', option_a:'Urge', option_b:'Stress', option_c:'Overflow', option_d:'Functional', correct_answer:'b', explanation:'Stress incontinence = leak with cough.', memory_tip:'Stress = cough = leak', difficulty:'easy', importance:3, tags:['renal'], language:'english', verified:true, active:true },
];

async function seed() {
  console.log(`Seeding ${questions.length} questions...`);
  
  for (let i = 0; i < questions.length; i += BATCH) {
    const batch = questions.slice(i, i + BATCH);
    const { error } = await supabase.from('questions').insert(batch);
    if (error) {
      console.error(`❌ Batch ${i/BATCH + 1} failed:`, error.message);
    } else {
      console.log(`✅ Batch ${i/BATCH + 1} inserted (${batch.length} questions)`);
    }
  }
  
  console.log('✅ Seeding complete!');
}

seed().catch(console.error);