/**
 * Seed extra questions using service key
 */
const { createClient } = require('@supabase/supabase-js');
const KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkbHFzeHh6b3pqamFmbHdveWxwIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4NDgwMDk2NiwiZXhwIjoyMTAwMzc2OTY2fQ.yNPzM1V-xMZwM5MiL2qKb0DLUyKXJcua70OjoK_w4O4';
const supabase = createClient('https://kdlqsxxzozjjaflwoylp.supabase.co', KEY);

const extraQuestions = [
  // GK questions (15)
  {category:'General Knowledge', subcategory:'Bangladesh Affairs', question:'When did Bangladesh gain independence?', option_a:'1970', option_b:'1971', option_c:'1972', option_d:'1973', correct_answer:'b', explanation:'Bangladesh gained independence on December 16, 1971.', difficulty:'easy', active:true},
  {category:'General Knowledge', subcategory:'Bangladesh Affairs', question:'Who is the Father of the Nation of Bangladesh?', option_a:'Sheikh Hasina', option_b:'Bangabandhu Sheikh Mujibur Rahman', option_c:'Tajuddin Ahmad', option_d:'Ziaur Rahman', correct_answer:'b', explanation:'Bangabandhu Sheikh Mujibur Rahman is the Father of the Nation.', difficulty:'easy', active:true},
  {category:'General Knowledge', subcategory:'Bangladesh Affairs', question:'What is the national language of Bangladesh?', option_a:'English', option_b:'Bengali (Bangla)', option_c:'Urdu', option_d:'Arabic', correct_answer:'b', explanation:'The national language of Bangladesh is Bengali (Bangla).', difficulty:'easy', active:true},
  {category:'General Knowledge', subcategory:'Bangladesh Affairs', question:'What is the national flower of Bangladesh?', option_a:'Rose', option_b:'Water Lily (Shapla)', option_c:'Marigold', option_d:'Sunflower', correct_answer:'b', explanation:'The national flower of Bangladesh is the Water Lily (Shapla).', difficulty:'easy', active:true},
  {category:'General Knowledge', subcategory:'Bangladesh Affairs', question:'What is the national animal of Bangladesh?', option_a:'Tiger', option_b:'Royal Bengal Tiger', option_c:'Lion', option_d:'Elephant', correct_answer:'b', explanation:'The national animal of Bangladesh is the Royal Bengal Tiger.', difficulty:'easy', active:true},
  {category:'General Knowledge', subcategory:'Bangladesh Affairs', question:'What is the currency of Bangladesh?', option_a:'Rupee', option_b:'Taka', option_c:'Dollar', option_d:'Rial', correct_answer:'b', explanation:'The currency of Bangladesh is the Taka (BDT).', difficulty:'easy', active:true},
  {category:'General Knowledge', subcategory:'Bangladesh Affairs', question:'When is Victory Day celebrated in Bangladesh?', option_a:'March 26', option_b:'December 16', option_c:'February 21', option_d:'August 15', correct_answer:'b', explanation:'Victory Day is celebrated on December 16.', difficulty:'easy', active:true},
  {category:'General Knowledge', subcategory:'Bangladesh Affairs', question:'What is the main export product of Bangladesh?', option_a:'Jute', option_b:'Tea', option_c:'Ready-made garments', option_d:'Leather', correct_answer:'c', explanation:'RMG accounts for approximately 80% of exports.', difficulty:'medium', active:true},
  {category:'General Knowledge', subcategory:'Bangladesh Affairs', question:'Which is the largest sea port in Bangladesh?', option_a:'Mongla', option_b:'Chittagong', option_c:'Paira', option_d:'Dhaka', correct_answer:'b', explanation:'Chittagong Port is the largest seaport.', difficulty:'easy', active:true},
  {category:'General Knowledge', subcategory:'International Affairs', question:'Which is the largest country by area?', option_a:'China', option_b:'USA', option_c:'Russia', option_d:'Canada', correct_answer:'c', explanation:'Russia is the largest country at 17.1 million sq km.', difficulty:'easy', active:true},
  {category:'General Knowledge', subcategory:'International Affairs', question:'Which is the most populous country?', option_a:'China', option_b:'India', option_c:'USA', option_d:'Indonesia', correct_answer:'b', explanation:'India has over 1.4 billion people.', difficulty:'easy', active:true},
  {category:'General Knowledge', subcategory:'Current Affairs', question:'Who is the current Prime Minister of Bangladesh?', option_a:'Khaleda Zia', option_b:'Sheikh Hasina', option_c:'Muhammad Yunus', option_d:'Tajuddin Ahmad', correct_answer:'b', explanation:'Sheikh Hasina has been Prime Minister since 2009.', difficulty:'easy', active:true},
  {category:'General Knowledge', subcategory:'Current Affairs', question:'What is the current UN Secretary-General name?', option_a:'Ban Ki-moon', option_b:'António Guterres', option_c:'Kofi Annan', option_d:'Boutros Boutros-Ghali', correct_answer:'b', explanation:'António Guterres has been UN Secretary-General since 2017.', difficulty:'medium', active:true},
  {category:'General Knowledge', subcategory:'Science & Technology', question:'What is the chemical symbol for water?', option_a:'H2O', option_b:'CO2', option_c:'NaCl', option_d:'O2', correct_answer:'a', explanation:'Water is H2O.', difficulty:'easy', active:true},
  {category:'General Knowledge', subcategory:'Science & Technology', question:'What is the largest planet in our solar system?', option_a:'Saturn', option_b:'Jupiter', option_c:'Neptune', option_d:'Uranus', correct_answer:'b', explanation:'Jupiter is the largest planet.', difficulty:'easy', active:true},
  // English questions (15)
  {category:'English', subcategory:'Grammar', question:'What is the plural of "child"?', option_a:'Childs', option_b:'Childes', option_c:'Children', option_d:'Childrens', correct_answer:'c', explanation:'The plural of child is children.', difficulty:'easy', active:true},
  {category:'English', subcategory:'Grammar', question:'Which sentence is correct?', option_a:'He go to school', option_b:'He goes to school', option_c:'He going to school', option_d:'He gone to school', correct_answer:'b', explanation:'Third person singular takes -s.', difficulty:'easy', active:true},
  {category:'English', subcategory:'Grammar', question:'What is the past tense of "run"?', option_a:'Runned', option_b:'Ran', option_c:'Run', option_d:'Running', correct_answer:'b', explanation:'Ran is the past tense of run.', difficulty:'easy', active:true},
  {category:'English', subcategory:'Grammar', question:'Which word is a conjunction?', option_a:'Quickly', option_b:'Because', option_c:'Beautiful', option_d:'Run', correct_answer:'b', explanation:'Because is a subordinating conjunction.', difficulty:'easy', active:true},
  {category:'English', subcategory:'Vocabulary', question:'What is the meaning of "benevolent"?', option_a:'Kind and generous', option_b:'Cruel and mean', option_c:'Lazy', option_d:'Angry', correct_answer:'a', explanation:'Benevolent means kind and generous.', difficulty:'medium', active:true},
  {category:'English', subcategory:'Vocabulary', question:'What is the meaning of "ambiguous"?', option_a:'Clear', option_b:'Having multiple meanings', option_c:'Simple', option_d:'Direct', correct_answer:'b', explanation:'Ambiguous means having multiple meanings.', difficulty:'medium', active:true},
  {category:'English', subcategory:'Vocabulary', question:'What is the meaning of "eloquent"?', option_a:'Fluent and persuasive', option_b:'Quiet', option_c:'Confused', option_d:'Rude', correct_answer:'a', explanation:'Eloquent means fluent and persuasive.', difficulty:'medium', active:true},
  {category:'English', subcategory:'Vocabulary', question:'What is the meaning of "gratitude"?', option_a:'Thankfulness', option_b:'Anger', option_c:'Sadness', option_d:'Jealousy', correct_answer:'a', explanation:'Gratitude means thankfulness.', difficulty:'easy', active:true},
  {category:'English', subcategory:'Vocabulary', question:'What is the meaning of "hostile"?', option_a:'Friendly', option_b:'Unfriendly and aggressive', option_c:'Happy', option_d:'Peaceful', correct_answer:'b', explanation:'Hostile means unfriendly and aggressive.', difficulty:'easy', active:true},
  {category:'English', subcategory:'Comprehension', question:'Read: "The sun rises in the east." What does the sun do?', option_a:'Sets', option_b:'Rises', option_c:'Hides', option_d:'Shines', correct_answer:'b', explanation:'The passage states the sun rises.', difficulty:'easy', active:true},
  {category:'English', subcategory:'Comprehension', question:'Read: "Water boils at 100°C." At what temperature does water boil?', option_a:'50°C', option_b:'75°C', option_c:'100°C', option_d:'125°C', correct_answer:'c', explanation:'Water boils at 100°C.', difficulty:'easy', active:true},
  {category:'English', subcategory:'Comprehension', question:'Read: "The capital of Bangladesh is Dhaka." What is the capital?', option_a:'Chittagong', option_b:'Dhaka', option_c:'Sylhet', option_d:'Rajshahi', correct_answer:'b', explanation:'Dhaka is the capital.', difficulty:'easy', active:true},
  {category:'English', subcategory:'Grammar', question:'What is the antonym of "generous"?', option_a:'Kind', option_b:'Stingy', option_c:'Helpful', option_d:'Charitable', correct_answer:'b', explanation:'Stingy is the opposite of generous.', difficulty:'medium', active:true},
  {category:'English', subcategory:'Grammar', question:'Which word is a pronoun?', option_a:'Table', option_b:'They', option_c:'Run', option_d:'Beautiful', correct_answer:'b', explanation:'They is a personal pronoun.', difficulty:'easy', active:true},
  {category:'English', subcategory:'Grammar', question:'What is the correct spelling?', option_a:'Recieve', option_b:'Receive', option_c:'Receeve', option_d:'Receve', correct_answer:'b', explanation:'The correct spelling is receive.', difficulty:'medium', active:true},
  // Bangla questions (10)
  {category:'Bangla', subcategory:'Grammar', question:'বাংলা ভাষার উৎপত্তি কোন ভাষা থেকে?', option_a:'সংস্কৃত', option_b:'প্রাকৃত', option_c:'পালি', option_d:'হিন্দি', correct_answer:'a', explanation:'বাংলা ভাষার উৎপত্তি সংস্কৃত ভাষা থেকে।', difficulty:'easy', active:true},
  {category:'Bangla', subcategory:'Grammar', question:'বাংলা বর্ণমালায় মোট কয়টি বর্ণ আছে?', option_a:'৪৪টি', option_b:'৫০টি', option_c:'৫২টি', option_d:'৪৮টি', correct_answer:'b', explanation:'বাংলা বর্ণমালায় মোট ৫০টি বর্ণ রয়েছে।', difficulty:'easy', active:true},
  {category:'Bangla', subcategory:'Literature', question:'রবীন্দ্রনাথ ঠাকুর কত সালে নোবেল পুরস্কার পান?', option_a:'১৯১১', option_b:'১৯১২', option_c:'১৯১৩', option_d:'১৯১৪', correct_answer:'c', explanation:'রবীন্দ্রনাথ ঠাকুর ১৯১৩ সালে নোবেল পুরস্কার পান।', difficulty:'easy', active:true},
  {category:'Bangla', subcategory:'Literature', question:'বাংলা সাহিত্যের প্রথম মহাকাব্য কোনটি?', option_a:'মেঘনাদবধ কাব্য', option_b:'বৈষ্ণব পদাবলী', option_c:'শ্রীকৃষ্ণকীর্তন', option_d:'চর্যাপদ', correct_answer:'c', explanation:'শ্রীকৃষ্ণকীর্তন বাংলা সাহিত্যের প্রথম মহাকাব্য।', difficulty:'medium', active:true},
  {category:'Bangla', subcategory:'Composition', question:'রচনার মূল অংশকে কী বলে?', option_a:'ভূমিকা', option_b:'বক্তব্য', option_c:'উপসংহার', option_d:'শিরোনাম', correct_answer:'b', explanation:'রচনার মূল অংশকে বক্তব্য বা মূল আলোচনা বলে।', difficulty:'easy', active:true},
  {category:'Bangla', subcategory:'Grammar', question:'কোনটি শুদ্ধ বানান?', option_a:'মুমুর্ষু', option_b:'মুমূর্ষু', option_c:'মুমুর্ষূ', option_d:'মুমুর্ষু', correct_answer:'b', explanation:'শুদ্ধ বানান "মুমূর্ষু"।', difficulty:'medium', active:true},
  {category:'Bangla', subcategory:'Grammar', question:'বাংলা ভাষায় কয়টি স্বরবর্ণ আছে?', option_a:'১০টি', option_b:'১১টি', option_c:'১২টি', option_d:'১৩টি', correct_answer:'b', explanation:'বাংলা ভাষায় ১১টি স্বরবর্ণ আছে।', difficulty:'easy', active:true},
  {category:'Bangla', subcategory:'Grammar', question:'কোনটি তৎসম শব্দ?', option_a:'চাঁদ', option_b:'বৃষ্টি', option_c:'চন্দ্র', option_d:'পানি', correct_answer:'c', explanation:'চন্দ্র একটি তৎসম শব্দ।', difficulty:'medium', active:true},
  {category:'Bangla', subcategory:'Grammar', question:'বাংলা ভাষায় কয়টি কারক আছে?', option_a:'৫টি', option_b:'৬টি', option_c:'৭টি', option_d:'৮টি', correct_answer:'b', explanation:'বাংলা ভাষায় ৬টি কারক আছে।', difficulty:'medium', active:true},
  {category:'Bangla', subcategory:'Grammar', question:'কোনটি দেশি শব্দ?', option_a:'চেয়ার', option_b:'কলম', option_c:'চুলা', option_d:'বই', correct_answer:'c', explanation:'চুলা একটি দেশি শব্দ।', difficulty:'medium', active:true},
];

async function seed() {
  console.log('Seeding extra questions...');
  for (let i = 0; i < extraQuestions.length; i += 50) {
    const batch = extraQuestions.slice(i, i + 50);
    const { error } = await supabase.from('questions').insert(batch);
    if (error) console.error('Batch failed:', error.message);
    else console.log(`Inserted ${batch.length} questions`);
  }
  const { count } = await supabase.from('questions').select('*', {count:'exact',head:true});
  console.log('Total questions now:', count);
}
seed();