-- Bangla and English MCQ pack
-- Run after the questions table exists

BEGIN;

INSERT INTO public.questions (category, subcategory, question, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, active) VALUES
('English', 'Synonyms and Antonyms', 'Quick revision: Choose the synonym of "rapid".', 'Slow', 'Quick', 'Weak', 'Late', 'b', 'Rapid means quick or fast.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For exam preparation: Choose the synonym of "rapid".', 'Slow', 'Quick', 'Weak', 'Late', 'b', 'Rapid means quick or fast.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a classroom drill: Choose the synonym of "rapid".', 'Slow', 'Quick', 'Weak', 'Late', 'b', 'Rapid means quick or fast.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For rapid recall: Choose the synonym of "rapid".', 'Slow', 'Quick', 'Weak', 'Late', 'b', 'Rapid means quick or fast.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'During final revision: Choose the synonym of "rapid".', 'Slow', 'Quick', 'Weak', 'Late', 'b', 'Rapid means quick or fast.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a mock test: Choose the synonym of "rapid".', 'Slow', 'Quick', 'Weak', 'Late', 'b', 'Rapid means quick or fast.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For topic review: Choose the synonym of "rapid".', 'Slow', 'Quick', 'Weak', 'Late', 'b', 'Rapid means quick or fast.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For short-answer practice: Choose the synonym of "rapid".', 'Slow', 'Quick', 'Weak', 'Late', 'b', 'Rapid means quick or fast.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a viva session: Choose the synonym of "rapid".', 'Slow', 'Quick', 'Weak', 'Late', 'b', 'Rapid means quick or fast.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'While revising the topic: Choose the synonym of "rapid".', 'Slow', 'Quick', 'Weak', 'Late', 'b', 'Rapid means quick or fast.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For concept clarity: Choose the synonym of "rapid".', 'Slow', 'Quick', 'Weak', 'Late', 'b', 'Rapid means quick or fast.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a question-bank drill: Choose the synonym of "rapid".', 'Slow', 'Quick', 'Weak', 'Late', 'b', 'Rapid means quick or fast.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For a one-mark recall: Choose the synonym of "rapid".', 'Slow', 'Quick', 'Weak', 'Late', 'b', 'Rapid means quick or fast.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a test series: Choose the synonym of "rapid".', 'Slow', 'Quick', 'Weak', 'Late', 'b', 'Rapid means quick or fast.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For last-minute revision: Choose the synonym of "rapid".', 'Slow', 'Quick', 'Weak', 'Late', 'b', 'Rapid means quick or fast.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a learning session: Choose the synonym of "rapid".', 'Slow', 'Quick', 'Weak', 'Late', 'b', 'Rapid means quick or fast.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For high-yield revision: Choose the synonym of "rapid".', 'Slow', 'Quick', 'Weak', 'Late', 'b', 'Rapid means quick or fast.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For practice mode: Choose the synonym of "rapid".', 'Slow', 'Quick', 'Weak', 'Late', 'b', 'Rapid means quick or fast.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In exam mode: Choose the synonym of "rapid".', 'Slow', 'Quick', 'Weak', 'Late', 'b', 'Rapid means quick or fast.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For quick study: Choose the synonym of "rapid".', 'Slow', 'Quick', 'Weak', 'Late', 'b', 'Rapid means quick or fast.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For structured revision: Choose the synonym of "rapid".', 'Slow', 'Quick', 'Weak', 'Late', 'b', 'Rapid means quick or fast.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a revision sheet: Choose the synonym of "rapid".', 'Slow', 'Quick', 'Weak', 'Late', 'b', 'Rapid means quick or fast.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For mastery practice: Choose the synonym of "rapid".', 'Slow', 'Quick', 'Weak', 'Late', 'b', 'Rapid means quick or fast.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a focused review: Choose the synonym of "rapid".', 'Slow', 'Quick', 'Weak', 'Late', 'b', 'Rapid means quick or fast.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For common exam prep: Choose the synonym of "rapid".', 'Slow', 'Quick', 'Weak', 'Late', 'b', 'Rapid means quick or fast.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For fast learning: Choose the synonym of "rapid".', 'Slow', 'Quick', 'Weak', 'Late', 'b', 'Rapid means quick or fast.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In an assessment drill: Choose the synonym of "rapid".', 'Slow', 'Quick', 'Weak', 'Late', 'b', 'Rapid means quick or fast.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For paper practice: Choose the synonym of "rapid".', 'Slow', 'Quick', 'Weak', 'Late', 'b', 'Rapid means quick or fast.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a recall exercise: Choose the synonym of "rapid".', 'Slow', 'Quick', 'Weak', 'Late', 'b', 'Rapid means quick or fast.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For a final check: Choose the synonym of "rapid".', 'Slow', 'Quick', 'Weak', 'Late', 'b', 'Rapid means quick or fast.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a topic-wise test: Choose the synonym of "rapid".', 'Slow', 'Quick', 'Weak', 'Late', 'b', 'Rapid means quick or fast.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For basic concept revision: Choose the synonym of "rapid".', 'Slow', 'Quick', 'Weak', 'Late', 'b', 'Rapid means quick or fast.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For easy memory: Choose the synonym of "rapid".', 'Slow', 'Quick', 'Weak', 'Late', 'b', 'Rapid means quick or fast.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a bedside review: Choose the synonym of "rapid".', 'Slow', 'Quick', 'Weak', 'Late', 'b', 'Rapid means quick or fast.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For study notes: Choose the synonym of "rapid".', 'Slow', 'Quick', 'Weak', 'Late', 'b', 'Rapid means quick or fast.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a revision round: Choose the synonym of "rapid".', 'Slow', 'Quick', 'Weak', 'Late', 'b', 'Rapid means quick or fast.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For a quick quiz: Choose the synonym of "rapid".', 'Slow', 'Quick', 'Weak', 'Late', 'b', 'Rapid means quick or fast.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In an MCQ session: Choose the synonym of "rapid".', 'Slow', 'Quick', 'Weak', 'Late', 'b', 'Rapid means quick or fast.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For practical preparation: Choose the synonym of "rapid".', 'Slow', 'Quick', 'Weak', 'Late', 'b', 'Rapid means quick or fast.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'As a quick reminder: Choose the synonym of "rapid".', 'Slow', 'Quick', 'Weak', 'Late', 'b', 'Rapid means quick or fast.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a serious revision: Choose the synonym of "rapid".', 'Slow', 'Quick', 'Weak', 'Late', 'b', 'Rapid means quick or fast.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For fast practice: Choose the synonym of "rapid".', 'Slow', 'Quick', 'Weak', 'Late', 'b', 'Rapid means quick or fast.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a focused session: Choose the synonym of "rapid".', 'Slow', 'Quick', 'Weak', 'Late', 'b', 'Rapid means quick or fast.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For exam confidence: Choose the synonym of "rapid".', 'Slow', 'Quick', 'Weak', 'Late', 'b', 'Rapid means quick or fast.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'During study time: Choose the synonym of "rapid".', 'Slow', 'Quick', 'Weak', 'Late', 'b', 'Rapid means quick or fast.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For a final look: Choose the synonym of "rapid".', 'Slow', 'Quick', 'Weak', 'Late', 'b', 'Rapid means quick or fast.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In an active recall session: Choose the synonym of "rapid".', 'Slow', 'Quick', 'Weak', 'Late', 'b', 'Rapid means quick or fast.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For a topic recap: Choose the synonym of "rapid".', 'Slow', 'Quick', 'Weak', 'Late', 'b', 'Rapid means quick or fast.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a fast review: Choose the synonym of "rapid".', 'Slow', 'Quick', 'Weak', 'Late', 'b', 'Rapid means quick or fast.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For high focus: Choose the synonym of "rapid".', 'Slow', 'Quick', 'Weak', 'Late', 'b', 'Rapid means quick or fast.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'Quick revision: Choose the synonym of "large".', 'Big', 'Tiny', 'Short', 'Narrow', 'a', 'Large means big.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For exam preparation: Choose the synonym of "large".', 'Big', 'Tiny', 'Short', 'Narrow', 'a', 'Large means big.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a classroom drill: Choose the synonym of "large".', 'Big', 'Tiny', 'Short', 'Narrow', 'a', 'Large means big.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For rapid recall: Choose the synonym of "large".', 'Big', 'Tiny', 'Short', 'Narrow', 'a', 'Large means big.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'During final revision: Choose the synonym of "large".', 'Big', 'Tiny', 'Short', 'Narrow', 'a', 'Large means big.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a mock test: Choose the synonym of "large".', 'Big', 'Tiny', 'Short', 'Narrow', 'a', 'Large means big.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For topic review: Choose the synonym of "large".', 'Big', 'Tiny', 'Short', 'Narrow', 'a', 'Large means big.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For short-answer practice: Choose the synonym of "large".', 'Big', 'Tiny', 'Short', 'Narrow', 'a', 'Large means big.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a viva session: Choose the synonym of "large".', 'Big', 'Tiny', 'Short', 'Narrow', 'a', 'Large means big.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'While revising the topic: Choose the synonym of "large".', 'Big', 'Tiny', 'Short', 'Narrow', 'a', 'Large means big.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For concept clarity: Choose the synonym of "large".', 'Big', 'Tiny', 'Short', 'Narrow', 'a', 'Large means big.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a question-bank drill: Choose the synonym of "large".', 'Big', 'Tiny', 'Short', 'Narrow', 'a', 'Large means big.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For a one-mark recall: Choose the synonym of "large".', 'Big', 'Tiny', 'Short', 'Narrow', 'a', 'Large means big.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a test series: Choose the synonym of "large".', 'Big', 'Tiny', 'Short', 'Narrow', 'a', 'Large means big.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For last-minute revision: Choose the synonym of "large".', 'Big', 'Tiny', 'Short', 'Narrow', 'a', 'Large means big.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a learning session: Choose the synonym of "large".', 'Big', 'Tiny', 'Short', 'Narrow', 'a', 'Large means big.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For high-yield revision: Choose the synonym of "large".', 'Big', 'Tiny', 'Short', 'Narrow', 'a', 'Large means big.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For practice mode: Choose the synonym of "large".', 'Big', 'Tiny', 'Short', 'Narrow', 'a', 'Large means big.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In exam mode: Choose the synonym of "large".', 'Big', 'Tiny', 'Short', 'Narrow', 'a', 'Large means big.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For quick study: Choose the synonym of "large".', 'Big', 'Tiny', 'Short', 'Narrow', 'a', 'Large means big.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For structured revision: Choose the synonym of "large".', 'Big', 'Tiny', 'Short', 'Narrow', 'a', 'Large means big.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a revision sheet: Choose the synonym of "large".', 'Big', 'Tiny', 'Short', 'Narrow', 'a', 'Large means big.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For mastery practice: Choose the synonym of "large".', 'Big', 'Tiny', 'Short', 'Narrow', 'a', 'Large means big.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a focused review: Choose the synonym of "large".', 'Big', 'Tiny', 'Short', 'Narrow', 'a', 'Large means big.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For common exam prep: Choose the synonym of "large".', 'Big', 'Tiny', 'Short', 'Narrow', 'a', 'Large means big.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For fast learning: Choose the synonym of "large".', 'Big', 'Tiny', 'Short', 'Narrow', 'a', 'Large means big.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In an assessment drill: Choose the synonym of "large".', 'Big', 'Tiny', 'Short', 'Narrow', 'a', 'Large means big.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For paper practice: Choose the synonym of "large".', 'Big', 'Tiny', 'Short', 'Narrow', 'a', 'Large means big.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a recall exercise: Choose the synonym of "large".', 'Big', 'Tiny', 'Short', 'Narrow', 'a', 'Large means big.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For a final check: Choose the synonym of "large".', 'Big', 'Tiny', 'Short', 'Narrow', 'a', 'Large means big.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a topic-wise test: Choose the synonym of "large".', 'Big', 'Tiny', 'Short', 'Narrow', 'a', 'Large means big.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For basic concept revision: Choose the synonym of "large".', 'Big', 'Tiny', 'Short', 'Narrow', 'a', 'Large means big.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For easy memory: Choose the synonym of "large".', 'Big', 'Tiny', 'Short', 'Narrow', 'a', 'Large means big.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a bedside review: Choose the synonym of "large".', 'Big', 'Tiny', 'Short', 'Narrow', 'a', 'Large means big.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For study notes: Choose the synonym of "large".', 'Big', 'Tiny', 'Short', 'Narrow', 'a', 'Large means big.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a revision round: Choose the synonym of "large".', 'Big', 'Tiny', 'Short', 'Narrow', 'a', 'Large means big.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For a quick quiz: Choose the synonym of "large".', 'Big', 'Tiny', 'Short', 'Narrow', 'a', 'Large means big.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In an MCQ session: Choose the synonym of "large".', 'Big', 'Tiny', 'Short', 'Narrow', 'a', 'Large means big.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For practical preparation: Choose the synonym of "large".', 'Big', 'Tiny', 'Short', 'Narrow', 'a', 'Large means big.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'As a quick reminder: Choose the synonym of "large".', 'Big', 'Tiny', 'Short', 'Narrow', 'a', 'Large means big.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a serious revision: Choose the synonym of "large".', 'Big', 'Tiny', 'Short', 'Narrow', 'a', 'Large means big.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For fast practice: Choose the synonym of "large".', 'Big', 'Tiny', 'Short', 'Narrow', 'a', 'Large means big.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a focused session: Choose the synonym of "large".', 'Big', 'Tiny', 'Short', 'Narrow', 'a', 'Large means big.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For exam confidence: Choose the synonym of "large".', 'Big', 'Tiny', 'Short', 'Narrow', 'a', 'Large means big.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'During study time: Choose the synonym of "large".', 'Big', 'Tiny', 'Short', 'Narrow', 'a', 'Large means big.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For a final look: Choose the synonym of "large".', 'Big', 'Tiny', 'Short', 'Narrow', 'a', 'Large means big.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In an active recall session: Choose the synonym of "large".', 'Big', 'Tiny', 'Short', 'Narrow', 'a', 'Large means big.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For a topic recap: Choose the synonym of "large".', 'Big', 'Tiny', 'Short', 'Narrow', 'a', 'Large means big.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a fast review: Choose the synonym of "large".', 'Big', 'Tiny', 'Short', 'Narrow', 'a', 'Large means big.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For high focus: Choose the synonym of "large".', 'Big', 'Tiny', 'Short', 'Narrow', 'a', 'Large means big.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'Quick revision: Choose the synonym of "happy".', 'Sad', 'Joyful', 'Angry', 'Tired', 'b', 'Happy means joyful.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For exam preparation: Choose the synonym of "happy".', 'Sad', 'Joyful', 'Angry', 'Tired', 'b', 'Happy means joyful.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a classroom drill: Choose the synonym of "happy".', 'Sad', 'Joyful', 'Angry', 'Tired', 'b', 'Happy means joyful.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For rapid recall: Choose the synonym of "happy".', 'Sad', 'Joyful', 'Angry', 'Tired', 'b', 'Happy means joyful.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'During final revision: Choose the synonym of "happy".', 'Sad', 'Joyful', 'Angry', 'Tired', 'b', 'Happy means joyful.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a mock test: Choose the synonym of "happy".', 'Sad', 'Joyful', 'Angry', 'Tired', 'b', 'Happy means joyful.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For topic review: Choose the synonym of "happy".', 'Sad', 'Joyful', 'Angry', 'Tired', 'b', 'Happy means joyful.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For short-answer practice: Choose the synonym of "happy".', 'Sad', 'Joyful', 'Angry', 'Tired', 'b', 'Happy means joyful.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a viva session: Choose the synonym of "happy".', 'Sad', 'Joyful', 'Angry', 'Tired', 'b', 'Happy means joyful.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'While revising the topic: Choose the synonym of "happy".', 'Sad', 'Joyful', 'Angry', 'Tired', 'b', 'Happy means joyful.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For concept clarity: Choose the synonym of "happy".', 'Sad', 'Joyful', 'Angry', 'Tired', 'b', 'Happy means joyful.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a question-bank drill: Choose the synonym of "happy".', 'Sad', 'Joyful', 'Angry', 'Tired', 'b', 'Happy means joyful.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For a one-mark recall: Choose the synonym of "happy".', 'Sad', 'Joyful', 'Angry', 'Tired', 'b', 'Happy means joyful.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a test series: Choose the synonym of "happy".', 'Sad', 'Joyful', 'Angry', 'Tired', 'b', 'Happy means joyful.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For last-minute revision: Choose the synonym of "happy".', 'Sad', 'Joyful', 'Angry', 'Tired', 'b', 'Happy means joyful.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a learning session: Choose the synonym of "happy".', 'Sad', 'Joyful', 'Angry', 'Tired', 'b', 'Happy means joyful.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For high-yield revision: Choose the synonym of "happy".', 'Sad', 'Joyful', 'Angry', 'Tired', 'b', 'Happy means joyful.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For practice mode: Choose the synonym of "happy".', 'Sad', 'Joyful', 'Angry', 'Tired', 'b', 'Happy means joyful.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In exam mode: Choose the synonym of "happy".', 'Sad', 'Joyful', 'Angry', 'Tired', 'b', 'Happy means joyful.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For quick study: Choose the synonym of "happy".', 'Sad', 'Joyful', 'Angry', 'Tired', 'b', 'Happy means joyful.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For structured revision: Choose the synonym of "happy".', 'Sad', 'Joyful', 'Angry', 'Tired', 'b', 'Happy means joyful.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a revision sheet: Choose the synonym of "happy".', 'Sad', 'Joyful', 'Angry', 'Tired', 'b', 'Happy means joyful.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For mastery practice: Choose the synonym of "happy".', 'Sad', 'Joyful', 'Angry', 'Tired', 'b', 'Happy means joyful.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a focused review: Choose the synonym of "happy".', 'Sad', 'Joyful', 'Angry', 'Tired', 'b', 'Happy means joyful.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For common exam prep: Choose the synonym of "happy".', 'Sad', 'Joyful', 'Angry', 'Tired', 'b', 'Happy means joyful.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For fast learning: Choose the synonym of "happy".', 'Sad', 'Joyful', 'Angry', 'Tired', 'b', 'Happy means joyful.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In an assessment drill: Choose the synonym of "happy".', 'Sad', 'Joyful', 'Angry', 'Tired', 'b', 'Happy means joyful.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For paper practice: Choose the synonym of "happy".', 'Sad', 'Joyful', 'Angry', 'Tired', 'b', 'Happy means joyful.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a recall exercise: Choose the synonym of "happy".', 'Sad', 'Joyful', 'Angry', 'Tired', 'b', 'Happy means joyful.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For a final check: Choose the synonym of "happy".', 'Sad', 'Joyful', 'Angry', 'Tired', 'b', 'Happy means joyful.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a topic-wise test: Choose the synonym of "happy".', 'Sad', 'Joyful', 'Angry', 'Tired', 'b', 'Happy means joyful.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For basic concept revision: Choose the synonym of "happy".', 'Sad', 'Joyful', 'Angry', 'Tired', 'b', 'Happy means joyful.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For easy memory: Choose the synonym of "happy".', 'Sad', 'Joyful', 'Angry', 'Tired', 'b', 'Happy means joyful.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a bedside review: Choose the synonym of "happy".', 'Sad', 'Joyful', 'Angry', 'Tired', 'b', 'Happy means joyful.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For study notes: Choose the synonym of "happy".', 'Sad', 'Joyful', 'Angry', 'Tired', 'b', 'Happy means joyful.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a revision round: Choose the synonym of "happy".', 'Sad', 'Joyful', 'Angry', 'Tired', 'b', 'Happy means joyful.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For a quick quiz: Choose the synonym of "happy".', 'Sad', 'Joyful', 'Angry', 'Tired', 'b', 'Happy means joyful.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In an MCQ session: Choose the synonym of "happy".', 'Sad', 'Joyful', 'Angry', 'Tired', 'b', 'Happy means joyful.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For practical preparation: Choose the synonym of "happy".', 'Sad', 'Joyful', 'Angry', 'Tired', 'b', 'Happy means joyful.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'As a quick reminder: Choose the synonym of "happy".', 'Sad', 'Joyful', 'Angry', 'Tired', 'b', 'Happy means joyful.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a serious revision: Choose the synonym of "happy".', 'Sad', 'Joyful', 'Angry', 'Tired', 'b', 'Happy means joyful.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For fast practice: Choose the synonym of "happy".', 'Sad', 'Joyful', 'Angry', 'Tired', 'b', 'Happy means joyful.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a focused session: Choose the synonym of "happy".', 'Sad', 'Joyful', 'Angry', 'Tired', 'b', 'Happy means joyful.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For exam confidence: Choose the synonym of "happy".', 'Sad', 'Joyful', 'Angry', 'Tired', 'b', 'Happy means joyful.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'During study time: Choose the synonym of "happy".', 'Sad', 'Joyful', 'Angry', 'Tired', 'b', 'Happy means joyful.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For a final look: Choose the synonym of "happy".', 'Sad', 'Joyful', 'Angry', 'Tired', 'b', 'Happy means joyful.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In an active recall session: Choose the synonym of "happy".', 'Sad', 'Joyful', 'Angry', 'Tired', 'b', 'Happy means joyful.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For a topic recap: Choose the synonym of "happy".', 'Sad', 'Joyful', 'Angry', 'Tired', 'b', 'Happy means joyful.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a fast review: Choose the synonym of "happy".', 'Sad', 'Joyful', 'Angry', 'Tired', 'b', 'Happy means joyful.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For high focus: Choose the synonym of "happy".', 'Sad', 'Joyful', 'Angry', 'Tired', 'b', 'Happy means joyful.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'Quick revision: Choose the synonym of "start".', 'Begin', 'End', 'Break', 'Hide', 'a', 'Start means begin.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For exam preparation: Choose the synonym of "start".', 'Begin', 'End', 'Break', 'Hide', 'a', 'Start means begin.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a classroom drill: Choose the synonym of "start".', 'Begin', 'End', 'Break', 'Hide', 'a', 'Start means begin.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For rapid recall: Choose the synonym of "start".', 'Begin', 'End', 'Break', 'Hide', 'a', 'Start means begin.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'During final revision: Choose the synonym of "start".', 'Begin', 'End', 'Break', 'Hide', 'a', 'Start means begin.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a mock test: Choose the synonym of "start".', 'Begin', 'End', 'Break', 'Hide', 'a', 'Start means begin.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For topic review: Choose the synonym of "start".', 'Begin', 'End', 'Break', 'Hide', 'a', 'Start means begin.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For short-answer practice: Choose the synonym of "start".', 'Begin', 'End', 'Break', 'Hide', 'a', 'Start means begin.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a viva session: Choose the synonym of "start".', 'Begin', 'End', 'Break', 'Hide', 'a', 'Start means begin.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'While revising the topic: Choose the synonym of "start".', 'Begin', 'End', 'Break', 'Hide', 'a', 'Start means begin.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For concept clarity: Choose the synonym of "start".', 'Begin', 'End', 'Break', 'Hide', 'a', 'Start means begin.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a question-bank drill: Choose the synonym of "start".', 'Begin', 'End', 'Break', 'Hide', 'a', 'Start means begin.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For a one-mark recall: Choose the synonym of "start".', 'Begin', 'End', 'Break', 'Hide', 'a', 'Start means begin.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a test series: Choose the synonym of "start".', 'Begin', 'End', 'Break', 'Hide', 'a', 'Start means begin.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For last-minute revision: Choose the synonym of "start".', 'Begin', 'End', 'Break', 'Hide', 'a', 'Start means begin.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a learning session: Choose the synonym of "start".', 'Begin', 'End', 'Break', 'Hide', 'a', 'Start means begin.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For high-yield revision: Choose the synonym of "start".', 'Begin', 'End', 'Break', 'Hide', 'a', 'Start means begin.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For practice mode: Choose the synonym of "start".', 'Begin', 'End', 'Break', 'Hide', 'a', 'Start means begin.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In exam mode: Choose the synonym of "start".', 'Begin', 'End', 'Break', 'Hide', 'a', 'Start means begin.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For quick study: Choose the synonym of "start".', 'Begin', 'End', 'Break', 'Hide', 'a', 'Start means begin.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For structured revision: Choose the synonym of "start".', 'Begin', 'End', 'Break', 'Hide', 'a', 'Start means begin.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a revision sheet: Choose the synonym of "start".', 'Begin', 'End', 'Break', 'Hide', 'a', 'Start means begin.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For mastery practice: Choose the synonym of "start".', 'Begin', 'End', 'Break', 'Hide', 'a', 'Start means begin.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a focused review: Choose the synonym of "start".', 'Begin', 'End', 'Break', 'Hide', 'a', 'Start means begin.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For common exam prep: Choose the synonym of "start".', 'Begin', 'End', 'Break', 'Hide', 'a', 'Start means begin.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For fast learning: Choose the synonym of "start".', 'Begin', 'End', 'Break', 'Hide', 'a', 'Start means begin.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In an assessment drill: Choose the synonym of "start".', 'Begin', 'End', 'Break', 'Hide', 'a', 'Start means begin.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For paper practice: Choose the synonym of "start".', 'Begin', 'End', 'Break', 'Hide', 'a', 'Start means begin.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a recall exercise: Choose the synonym of "start".', 'Begin', 'End', 'Break', 'Hide', 'a', 'Start means begin.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For a final check: Choose the synonym of "start".', 'Begin', 'End', 'Break', 'Hide', 'a', 'Start means begin.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a topic-wise test: Choose the synonym of "start".', 'Begin', 'End', 'Break', 'Hide', 'a', 'Start means begin.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For basic concept revision: Choose the synonym of "start".', 'Begin', 'End', 'Break', 'Hide', 'a', 'Start means begin.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For easy memory: Choose the synonym of "start".', 'Begin', 'End', 'Break', 'Hide', 'a', 'Start means begin.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a bedside review: Choose the synonym of "start".', 'Begin', 'End', 'Break', 'Hide', 'a', 'Start means begin.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For study notes: Choose the synonym of "start".', 'Begin', 'End', 'Break', 'Hide', 'a', 'Start means begin.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a revision round: Choose the synonym of "start".', 'Begin', 'End', 'Break', 'Hide', 'a', 'Start means begin.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For a quick quiz: Choose the synonym of "start".', 'Begin', 'End', 'Break', 'Hide', 'a', 'Start means begin.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In an MCQ session: Choose the synonym of "start".', 'Begin', 'End', 'Break', 'Hide', 'a', 'Start means begin.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For practical preparation: Choose the synonym of "start".', 'Begin', 'End', 'Break', 'Hide', 'a', 'Start means begin.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'As a quick reminder: Choose the synonym of "start".', 'Begin', 'End', 'Break', 'Hide', 'a', 'Start means begin.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a serious revision: Choose the synonym of "start".', 'Begin', 'End', 'Break', 'Hide', 'a', 'Start means begin.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For fast practice: Choose the synonym of "start".', 'Begin', 'End', 'Break', 'Hide', 'a', 'Start means begin.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a focused session: Choose the synonym of "start".', 'Begin', 'End', 'Break', 'Hide', 'a', 'Start means begin.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For exam confidence: Choose the synonym of "start".', 'Begin', 'End', 'Break', 'Hide', 'a', 'Start means begin.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'During study time: Choose the synonym of "start".', 'Begin', 'End', 'Break', 'Hide', 'a', 'Start means begin.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For a final look: Choose the synonym of "start".', 'Begin', 'End', 'Break', 'Hide', 'a', 'Start means begin.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In an active recall session: Choose the synonym of "start".', 'Begin', 'End', 'Break', 'Hide', 'a', 'Start means begin.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For a topic recap: Choose the synonym of "start".', 'Begin', 'End', 'Break', 'Hide', 'a', 'Start means begin.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a fast review: Choose the synonym of "start".', 'Begin', 'End', 'Break', 'Hide', 'a', 'Start means begin.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For high focus: Choose the synonym of "start".', 'Begin', 'End', 'Break', 'Hide', 'a', 'Start means begin.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'Quick revision: Choose the antonym of "honest".', 'Truthful', 'Sincere', 'Dishonest', 'Kind', 'c', 'The opposite of honest is dishonest.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For exam preparation: Choose the antonym of "honest".', 'Truthful', 'Sincere', 'Dishonest', 'Kind', 'c', 'The opposite of honest is dishonest.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a classroom drill: Choose the antonym of "honest".', 'Truthful', 'Sincere', 'Dishonest', 'Kind', 'c', 'The opposite of honest is dishonest.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For rapid recall: Choose the antonym of "honest".', 'Truthful', 'Sincere', 'Dishonest', 'Kind', 'c', 'The opposite of honest is dishonest.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'During final revision: Choose the antonym of "honest".', 'Truthful', 'Sincere', 'Dishonest', 'Kind', 'c', 'The opposite of honest is dishonest.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a mock test: Choose the antonym of "honest".', 'Truthful', 'Sincere', 'Dishonest', 'Kind', 'c', 'The opposite of honest is dishonest.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For topic review: Choose the antonym of "honest".', 'Truthful', 'Sincere', 'Dishonest', 'Kind', 'c', 'The opposite of honest is dishonest.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For short-answer practice: Choose the antonym of "honest".', 'Truthful', 'Sincere', 'Dishonest', 'Kind', 'c', 'The opposite of honest is dishonest.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a viva session: Choose the antonym of "honest".', 'Truthful', 'Sincere', 'Dishonest', 'Kind', 'c', 'The opposite of honest is dishonest.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'While revising the topic: Choose the antonym of "honest".', 'Truthful', 'Sincere', 'Dishonest', 'Kind', 'c', 'The opposite of honest is dishonest.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For concept clarity: Choose the antonym of "honest".', 'Truthful', 'Sincere', 'Dishonest', 'Kind', 'c', 'The opposite of honest is dishonest.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a question-bank drill: Choose the antonym of "honest".', 'Truthful', 'Sincere', 'Dishonest', 'Kind', 'c', 'The opposite of honest is dishonest.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For a one-mark recall: Choose the antonym of "honest".', 'Truthful', 'Sincere', 'Dishonest', 'Kind', 'c', 'The opposite of honest is dishonest.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a test series: Choose the antonym of "honest".', 'Truthful', 'Sincere', 'Dishonest', 'Kind', 'c', 'The opposite of honest is dishonest.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For last-minute revision: Choose the antonym of "honest".', 'Truthful', 'Sincere', 'Dishonest', 'Kind', 'c', 'The opposite of honest is dishonest.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a learning session: Choose the antonym of "honest".', 'Truthful', 'Sincere', 'Dishonest', 'Kind', 'c', 'The opposite of honest is dishonest.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For high-yield revision: Choose the antonym of "honest".', 'Truthful', 'Sincere', 'Dishonest', 'Kind', 'c', 'The opposite of honest is dishonest.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For practice mode: Choose the antonym of "honest".', 'Truthful', 'Sincere', 'Dishonest', 'Kind', 'c', 'The opposite of honest is dishonest.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In exam mode: Choose the antonym of "honest".', 'Truthful', 'Sincere', 'Dishonest', 'Kind', 'c', 'The opposite of honest is dishonest.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For quick study: Choose the antonym of "honest".', 'Truthful', 'Sincere', 'Dishonest', 'Kind', 'c', 'The opposite of honest is dishonest.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For structured revision: Choose the antonym of "honest".', 'Truthful', 'Sincere', 'Dishonest', 'Kind', 'c', 'The opposite of honest is dishonest.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a revision sheet: Choose the antonym of "honest".', 'Truthful', 'Sincere', 'Dishonest', 'Kind', 'c', 'The opposite of honest is dishonest.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For mastery practice: Choose the antonym of "honest".', 'Truthful', 'Sincere', 'Dishonest', 'Kind', 'c', 'The opposite of honest is dishonest.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a focused review: Choose the antonym of "honest".', 'Truthful', 'Sincere', 'Dishonest', 'Kind', 'c', 'The opposite of honest is dishonest.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For common exam prep: Choose the antonym of "honest".', 'Truthful', 'Sincere', 'Dishonest', 'Kind', 'c', 'The opposite of honest is dishonest.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For fast learning: Choose the antonym of "honest".', 'Truthful', 'Sincere', 'Dishonest', 'Kind', 'c', 'The opposite of honest is dishonest.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In an assessment drill: Choose the antonym of "honest".', 'Truthful', 'Sincere', 'Dishonest', 'Kind', 'c', 'The opposite of honest is dishonest.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For paper practice: Choose the antonym of "honest".', 'Truthful', 'Sincere', 'Dishonest', 'Kind', 'c', 'The opposite of honest is dishonest.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a recall exercise: Choose the antonym of "honest".', 'Truthful', 'Sincere', 'Dishonest', 'Kind', 'c', 'The opposite of honest is dishonest.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For a final check: Choose the antonym of "honest".', 'Truthful', 'Sincere', 'Dishonest', 'Kind', 'c', 'The opposite of honest is dishonest.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a topic-wise test: Choose the antonym of "honest".', 'Truthful', 'Sincere', 'Dishonest', 'Kind', 'c', 'The opposite of honest is dishonest.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For basic concept revision: Choose the antonym of "honest".', 'Truthful', 'Sincere', 'Dishonest', 'Kind', 'c', 'The opposite of honest is dishonest.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For easy memory: Choose the antonym of "honest".', 'Truthful', 'Sincere', 'Dishonest', 'Kind', 'c', 'The opposite of honest is dishonest.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a bedside review: Choose the antonym of "honest".', 'Truthful', 'Sincere', 'Dishonest', 'Kind', 'c', 'The opposite of honest is dishonest.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For study notes: Choose the antonym of "honest".', 'Truthful', 'Sincere', 'Dishonest', 'Kind', 'c', 'The opposite of honest is dishonest.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a revision round: Choose the antonym of "honest".', 'Truthful', 'Sincere', 'Dishonest', 'Kind', 'c', 'The opposite of honest is dishonest.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For a quick quiz: Choose the antonym of "honest".', 'Truthful', 'Sincere', 'Dishonest', 'Kind', 'c', 'The opposite of honest is dishonest.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In an MCQ session: Choose the antonym of "honest".', 'Truthful', 'Sincere', 'Dishonest', 'Kind', 'c', 'The opposite of honest is dishonest.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For practical preparation: Choose the antonym of "honest".', 'Truthful', 'Sincere', 'Dishonest', 'Kind', 'c', 'The opposite of honest is dishonest.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'As a quick reminder: Choose the antonym of "honest".', 'Truthful', 'Sincere', 'Dishonest', 'Kind', 'c', 'The opposite of honest is dishonest.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a serious revision: Choose the antonym of "honest".', 'Truthful', 'Sincere', 'Dishonest', 'Kind', 'c', 'The opposite of honest is dishonest.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For fast practice: Choose the antonym of "honest".', 'Truthful', 'Sincere', 'Dishonest', 'Kind', 'c', 'The opposite of honest is dishonest.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a focused session: Choose the antonym of "honest".', 'Truthful', 'Sincere', 'Dishonest', 'Kind', 'c', 'The opposite of honest is dishonest.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For exam confidence: Choose the antonym of "honest".', 'Truthful', 'Sincere', 'Dishonest', 'Kind', 'c', 'The opposite of honest is dishonest.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'During study time: Choose the antonym of "honest".', 'Truthful', 'Sincere', 'Dishonest', 'Kind', 'c', 'The opposite of honest is dishonest.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For a final look: Choose the antonym of "honest".', 'Truthful', 'Sincere', 'Dishonest', 'Kind', 'c', 'The opposite of honest is dishonest.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In an active recall session: Choose the antonym of "honest".', 'Truthful', 'Sincere', 'Dishonest', 'Kind', 'c', 'The opposite of honest is dishonest.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For a topic recap: Choose the antonym of "honest".', 'Truthful', 'Sincere', 'Dishonest', 'Kind', 'c', 'The opposite of honest is dishonest.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a fast review: Choose the antonym of "honest".', 'Truthful', 'Sincere', 'Dishonest', 'Kind', 'c', 'The opposite of honest is dishonest.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For high focus: Choose the antonym of "honest".', 'Truthful', 'Sincere', 'Dishonest', 'Kind', 'c', 'The opposite of honest is dishonest.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'Quick revision: Choose the antonym of "early".', 'Before', 'Soon', 'Late', 'Quick', 'c', 'The opposite of early is late.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For exam preparation: Choose the antonym of "early".', 'Before', 'Soon', 'Late', 'Quick', 'c', 'The opposite of early is late.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a classroom drill: Choose the antonym of "early".', 'Before', 'Soon', 'Late', 'Quick', 'c', 'The opposite of early is late.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For rapid recall: Choose the antonym of "early".', 'Before', 'Soon', 'Late', 'Quick', 'c', 'The opposite of early is late.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'During final revision: Choose the antonym of "early".', 'Before', 'Soon', 'Late', 'Quick', 'c', 'The opposite of early is late.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a mock test: Choose the antonym of "early".', 'Before', 'Soon', 'Late', 'Quick', 'c', 'The opposite of early is late.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For topic review: Choose the antonym of "early".', 'Before', 'Soon', 'Late', 'Quick', 'c', 'The opposite of early is late.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For short-answer practice: Choose the antonym of "early".', 'Before', 'Soon', 'Late', 'Quick', 'c', 'The opposite of early is late.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a viva session: Choose the antonym of "early".', 'Before', 'Soon', 'Late', 'Quick', 'c', 'The opposite of early is late.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'While revising the topic: Choose the antonym of "early".', 'Before', 'Soon', 'Late', 'Quick', 'c', 'The opposite of early is late.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For concept clarity: Choose the antonym of "early".', 'Before', 'Soon', 'Late', 'Quick', 'c', 'The opposite of early is late.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a question-bank drill: Choose the antonym of "early".', 'Before', 'Soon', 'Late', 'Quick', 'c', 'The opposite of early is late.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For a one-mark recall: Choose the antonym of "early".', 'Before', 'Soon', 'Late', 'Quick', 'c', 'The opposite of early is late.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a test series: Choose the antonym of "early".', 'Before', 'Soon', 'Late', 'Quick', 'c', 'The opposite of early is late.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For last-minute revision: Choose the antonym of "early".', 'Before', 'Soon', 'Late', 'Quick', 'c', 'The opposite of early is late.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a learning session: Choose the antonym of "early".', 'Before', 'Soon', 'Late', 'Quick', 'c', 'The opposite of early is late.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For high-yield revision: Choose the antonym of "early".', 'Before', 'Soon', 'Late', 'Quick', 'c', 'The opposite of early is late.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For practice mode: Choose the antonym of "early".', 'Before', 'Soon', 'Late', 'Quick', 'c', 'The opposite of early is late.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In exam mode: Choose the antonym of "early".', 'Before', 'Soon', 'Late', 'Quick', 'c', 'The opposite of early is late.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For quick study: Choose the antonym of "early".', 'Before', 'Soon', 'Late', 'Quick', 'c', 'The opposite of early is late.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For structured revision: Choose the antonym of "early".', 'Before', 'Soon', 'Late', 'Quick', 'c', 'The opposite of early is late.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a revision sheet: Choose the antonym of "early".', 'Before', 'Soon', 'Late', 'Quick', 'c', 'The opposite of early is late.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For mastery practice: Choose the antonym of "early".', 'Before', 'Soon', 'Late', 'Quick', 'c', 'The opposite of early is late.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a focused review: Choose the antonym of "early".', 'Before', 'Soon', 'Late', 'Quick', 'c', 'The opposite of early is late.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For common exam prep: Choose the antonym of "early".', 'Before', 'Soon', 'Late', 'Quick', 'c', 'The opposite of early is late.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For fast learning: Choose the antonym of "early".', 'Before', 'Soon', 'Late', 'Quick', 'c', 'The opposite of early is late.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In an assessment drill: Choose the antonym of "early".', 'Before', 'Soon', 'Late', 'Quick', 'c', 'The opposite of early is late.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For paper practice: Choose the antonym of "early".', 'Before', 'Soon', 'Late', 'Quick', 'c', 'The opposite of early is late.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a recall exercise: Choose the antonym of "early".', 'Before', 'Soon', 'Late', 'Quick', 'c', 'The opposite of early is late.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For a final check: Choose the antonym of "early".', 'Before', 'Soon', 'Late', 'Quick', 'c', 'The opposite of early is late.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a topic-wise test: Choose the antonym of "early".', 'Before', 'Soon', 'Late', 'Quick', 'c', 'The opposite of early is late.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For basic concept revision: Choose the antonym of "early".', 'Before', 'Soon', 'Late', 'Quick', 'c', 'The opposite of early is late.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For easy memory: Choose the antonym of "early".', 'Before', 'Soon', 'Late', 'Quick', 'c', 'The opposite of early is late.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a bedside review: Choose the antonym of "early".', 'Before', 'Soon', 'Late', 'Quick', 'c', 'The opposite of early is late.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For study notes: Choose the antonym of "early".', 'Before', 'Soon', 'Late', 'Quick', 'c', 'The opposite of early is late.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a revision round: Choose the antonym of "early".', 'Before', 'Soon', 'Late', 'Quick', 'c', 'The opposite of early is late.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For a quick quiz: Choose the antonym of "early".', 'Before', 'Soon', 'Late', 'Quick', 'c', 'The opposite of early is late.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In an MCQ session: Choose the antonym of "early".', 'Before', 'Soon', 'Late', 'Quick', 'c', 'The opposite of early is late.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For practical preparation: Choose the antonym of "early".', 'Before', 'Soon', 'Late', 'Quick', 'c', 'The opposite of early is late.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'As a quick reminder: Choose the antonym of "early".', 'Before', 'Soon', 'Late', 'Quick', 'c', 'The opposite of early is late.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a serious revision: Choose the antonym of "early".', 'Before', 'Soon', 'Late', 'Quick', 'c', 'The opposite of early is late.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For fast practice: Choose the antonym of "early".', 'Before', 'Soon', 'Late', 'Quick', 'c', 'The opposite of early is late.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a focused session: Choose the antonym of "early".', 'Before', 'Soon', 'Late', 'Quick', 'c', 'The opposite of early is late.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For exam confidence: Choose the antonym of "early".', 'Before', 'Soon', 'Late', 'Quick', 'c', 'The opposite of early is late.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'During study time: Choose the antonym of "early".', 'Before', 'Soon', 'Late', 'Quick', 'c', 'The opposite of early is late.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For a final look: Choose the antonym of "early".', 'Before', 'Soon', 'Late', 'Quick', 'c', 'The opposite of early is late.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In an active recall session: Choose the antonym of "early".', 'Before', 'Soon', 'Late', 'Quick', 'c', 'The opposite of early is late.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For a topic recap: Choose the antonym of "early".', 'Before', 'Soon', 'Late', 'Quick', 'c', 'The opposite of early is late.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a fast review: Choose the antonym of "early".', 'Before', 'Soon', 'Late', 'Quick', 'c', 'The opposite of early is late.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For high focus: Choose the antonym of "early".', 'Before', 'Soon', 'Late', 'Quick', 'c', 'The opposite of early is late.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'Quick revision: Choose the antonym of "strong".', 'Powerful', 'Weak', 'Healthy', 'Brave', 'b', 'The opposite of strong is weak.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For exam preparation: Choose the antonym of "strong".', 'Powerful', 'Weak', 'Healthy', 'Brave', 'b', 'The opposite of strong is weak.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a classroom drill: Choose the antonym of "strong".', 'Powerful', 'Weak', 'Healthy', 'Brave', 'b', 'The opposite of strong is weak.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For rapid recall: Choose the antonym of "strong".', 'Powerful', 'Weak', 'Healthy', 'Brave', 'b', 'The opposite of strong is weak.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'During final revision: Choose the antonym of "strong".', 'Powerful', 'Weak', 'Healthy', 'Brave', 'b', 'The opposite of strong is weak.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a mock test: Choose the antonym of "strong".', 'Powerful', 'Weak', 'Healthy', 'Brave', 'b', 'The opposite of strong is weak.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For topic review: Choose the antonym of "strong".', 'Powerful', 'Weak', 'Healthy', 'Brave', 'b', 'The opposite of strong is weak.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For short-answer practice: Choose the antonym of "strong".', 'Powerful', 'Weak', 'Healthy', 'Brave', 'b', 'The opposite of strong is weak.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a viva session: Choose the antonym of "strong".', 'Powerful', 'Weak', 'Healthy', 'Brave', 'b', 'The opposite of strong is weak.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'While revising the topic: Choose the antonym of "strong".', 'Powerful', 'Weak', 'Healthy', 'Brave', 'b', 'The opposite of strong is weak.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For concept clarity: Choose the antonym of "strong".', 'Powerful', 'Weak', 'Healthy', 'Brave', 'b', 'The opposite of strong is weak.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a question-bank drill: Choose the antonym of "strong".', 'Powerful', 'Weak', 'Healthy', 'Brave', 'b', 'The opposite of strong is weak.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For a one-mark recall: Choose the antonym of "strong".', 'Powerful', 'Weak', 'Healthy', 'Brave', 'b', 'The opposite of strong is weak.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a test series: Choose the antonym of "strong".', 'Powerful', 'Weak', 'Healthy', 'Brave', 'b', 'The opposite of strong is weak.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For last-minute revision: Choose the antonym of "strong".', 'Powerful', 'Weak', 'Healthy', 'Brave', 'b', 'The opposite of strong is weak.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a learning session: Choose the antonym of "strong".', 'Powerful', 'Weak', 'Healthy', 'Brave', 'b', 'The opposite of strong is weak.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For high-yield revision: Choose the antonym of "strong".', 'Powerful', 'Weak', 'Healthy', 'Brave', 'b', 'The opposite of strong is weak.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For practice mode: Choose the antonym of "strong".', 'Powerful', 'Weak', 'Healthy', 'Brave', 'b', 'The opposite of strong is weak.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In exam mode: Choose the antonym of "strong".', 'Powerful', 'Weak', 'Healthy', 'Brave', 'b', 'The opposite of strong is weak.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For quick study: Choose the antonym of "strong".', 'Powerful', 'Weak', 'Healthy', 'Brave', 'b', 'The opposite of strong is weak.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For structured revision: Choose the antonym of "strong".', 'Powerful', 'Weak', 'Healthy', 'Brave', 'b', 'The opposite of strong is weak.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a revision sheet: Choose the antonym of "strong".', 'Powerful', 'Weak', 'Healthy', 'Brave', 'b', 'The opposite of strong is weak.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For mastery practice: Choose the antonym of "strong".', 'Powerful', 'Weak', 'Healthy', 'Brave', 'b', 'The opposite of strong is weak.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a focused review: Choose the antonym of "strong".', 'Powerful', 'Weak', 'Healthy', 'Brave', 'b', 'The opposite of strong is weak.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For common exam prep: Choose the antonym of "strong".', 'Powerful', 'Weak', 'Healthy', 'Brave', 'b', 'The opposite of strong is weak.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For fast learning: Choose the antonym of "strong".', 'Powerful', 'Weak', 'Healthy', 'Brave', 'b', 'The opposite of strong is weak.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In an assessment drill: Choose the antonym of "strong".', 'Powerful', 'Weak', 'Healthy', 'Brave', 'b', 'The opposite of strong is weak.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For paper practice: Choose the antonym of "strong".', 'Powerful', 'Weak', 'Healthy', 'Brave', 'b', 'The opposite of strong is weak.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a recall exercise: Choose the antonym of "strong".', 'Powerful', 'Weak', 'Healthy', 'Brave', 'b', 'The opposite of strong is weak.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For a final check: Choose the antonym of "strong".', 'Powerful', 'Weak', 'Healthy', 'Brave', 'b', 'The opposite of strong is weak.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a topic-wise test: Choose the antonym of "strong".', 'Powerful', 'Weak', 'Healthy', 'Brave', 'b', 'The opposite of strong is weak.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For basic concept revision: Choose the antonym of "strong".', 'Powerful', 'Weak', 'Healthy', 'Brave', 'b', 'The opposite of strong is weak.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For easy memory: Choose the antonym of "strong".', 'Powerful', 'Weak', 'Healthy', 'Brave', 'b', 'The opposite of strong is weak.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a bedside review: Choose the antonym of "strong".', 'Powerful', 'Weak', 'Healthy', 'Brave', 'b', 'The opposite of strong is weak.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For study notes: Choose the antonym of "strong".', 'Powerful', 'Weak', 'Healthy', 'Brave', 'b', 'The opposite of strong is weak.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a revision round: Choose the antonym of "strong".', 'Powerful', 'Weak', 'Healthy', 'Brave', 'b', 'The opposite of strong is weak.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For a quick quiz: Choose the antonym of "strong".', 'Powerful', 'Weak', 'Healthy', 'Brave', 'b', 'The opposite of strong is weak.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In an MCQ session: Choose the antonym of "strong".', 'Powerful', 'Weak', 'Healthy', 'Brave', 'b', 'The opposite of strong is weak.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For practical preparation: Choose the antonym of "strong".', 'Powerful', 'Weak', 'Healthy', 'Brave', 'b', 'The opposite of strong is weak.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'As a quick reminder: Choose the antonym of "strong".', 'Powerful', 'Weak', 'Healthy', 'Brave', 'b', 'The opposite of strong is weak.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a serious revision: Choose the antonym of "strong".', 'Powerful', 'Weak', 'Healthy', 'Brave', 'b', 'The opposite of strong is weak.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For fast practice: Choose the antonym of "strong".', 'Powerful', 'Weak', 'Healthy', 'Brave', 'b', 'The opposite of strong is weak.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a focused session: Choose the antonym of "strong".', 'Powerful', 'Weak', 'Healthy', 'Brave', 'b', 'The opposite of strong is weak.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For exam confidence: Choose the antonym of "strong".', 'Powerful', 'Weak', 'Healthy', 'Brave', 'b', 'The opposite of strong is weak.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'During study time: Choose the antonym of "strong".', 'Powerful', 'Weak', 'Healthy', 'Brave', 'b', 'The opposite of strong is weak.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For a final look: Choose the antonym of "strong".', 'Powerful', 'Weak', 'Healthy', 'Brave', 'b', 'The opposite of strong is weak.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In an active recall session: Choose the antonym of "strong".', 'Powerful', 'Weak', 'Healthy', 'Brave', 'b', 'The opposite of strong is weak.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For a topic recap: Choose the antonym of "strong".', 'Powerful', 'Weak', 'Healthy', 'Brave', 'b', 'The opposite of strong is weak.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a fast review: Choose the antonym of "strong".', 'Powerful', 'Weak', 'Healthy', 'Brave', 'b', 'The opposite of strong is weak.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For high focus: Choose the antonym of "strong".', 'Powerful', 'Weak', 'Healthy', 'Brave', 'b', 'The opposite of strong is weak.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'Quick revision: Choose the antonym of "increase".', 'Grow', 'Rise', 'Decrease', 'Improve', 'c', 'The opposite of increase is decrease.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For exam preparation: Choose the antonym of "increase".', 'Grow', 'Rise', 'Decrease', 'Improve', 'c', 'The opposite of increase is decrease.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a classroom drill: Choose the antonym of "increase".', 'Grow', 'Rise', 'Decrease', 'Improve', 'c', 'The opposite of increase is decrease.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For rapid recall: Choose the antonym of "increase".', 'Grow', 'Rise', 'Decrease', 'Improve', 'c', 'The opposite of increase is decrease.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'During final revision: Choose the antonym of "increase".', 'Grow', 'Rise', 'Decrease', 'Improve', 'c', 'The opposite of increase is decrease.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a mock test: Choose the antonym of "increase".', 'Grow', 'Rise', 'Decrease', 'Improve', 'c', 'The opposite of increase is decrease.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For topic review: Choose the antonym of "increase".', 'Grow', 'Rise', 'Decrease', 'Improve', 'c', 'The opposite of increase is decrease.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For short-answer practice: Choose the antonym of "increase".', 'Grow', 'Rise', 'Decrease', 'Improve', 'c', 'The opposite of increase is decrease.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a viva session: Choose the antonym of "increase".', 'Grow', 'Rise', 'Decrease', 'Improve', 'c', 'The opposite of increase is decrease.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'While revising the topic: Choose the antonym of "increase".', 'Grow', 'Rise', 'Decrease', 'Improve', 'c', 'The opposite of increase is decrease.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For concept clarity: Choose the antonym of "increase".', 'Grow', 'Rise', 'Decrease', 'Improve', 'c', 'The opposite of increase is decrease.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a question-bank drill: Choose the antonym of "increase".', 'Grow', 'Rise', 'Decrease', 'Improve', 'c', 'The opposite of increase is decrease.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For a one-mark recall: Choose the antonym of "increase".', 'Grow', 'Rise', 'Decrease', 'Improve', 'c', 'The opposite of increase is decrease.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a test series: Choose the antonym of "increase".', 'Grow', 'Rise', 'Decrease', 'Improve', 'c', 'The opposite of increase is decrease.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For last-minute revision: Choose the antonym of "increase".', 'Grow', 'Rise', 'Decrease', 'Improve', 'c', 'The opposite of increase is decrease.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a learning session: Choose the antonym of "increase".', 'Grow', 'Rise', 'Decrease', 'Improve', 'c', 'The opposite of increase is decrease.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For high-yield revision: Choose the antonym of "increase".', 'Grow', 'Rise', 'Decrease', 'Improve', 'c', 'The opposite of increase is decrease.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For practice mode: Choose the antonym of "increase".', 'Grow', 'Rise', 'Decrease', 'Improve', 'c', 'The opposite of increase is decrease.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In exam mode: Choose the antonym of "increase".', 'Grow', 'Rise', 'Decrease', 'Improve', 'c', 'The opposite of increase is decrease.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For quick study: Choose the antonym of "increase".', 'Grow', 'Rise', 'Decrease', 'Improve', 'c', 'The opposite of increase is decrease.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For structured revision: Choose the antonym of "increase".', 'Grow', 'Rise', 'Decrease', 'Improve', 'c', 'The opposite of increase is decrease.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a revision sheet: Choose the antonym of "increase".', 'Grow', 'Rise', 'Decrease', 'Improve', 'c', 'The opposite of increase is decrease.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For mastery practice: Choose the antonym of "increase".', 'Grow', 'Rise', 'Decrease', 'Improve', 'c', 'The opposite of increase is decrease.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a focused review: Choose the antonym of "increase".', 'Grow', 'Rise', 'Decrease', 'Improve', 'c', 'The opposite of increase is decrease.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For common exam prep: Choose the antonym of "increase".', 'Grow', 'Rise', 'Decrease', 'Improve', 'c', 'The opposite of increase is decrease.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For fast learning: Choose the antonym of "increase".', 'Grow', 'Rise', 'Decrease', 'Improve', 'c', 'The opposite of increase is decrease.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In an assessment drill: Choose the antonym of "increase".', 'Grow', 'Rise', 'Decrease', 'Improve', 'c', 'The opposite of increase is decrease.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For paper practice: Choose the antonym of "increase".', 'Grow', 'Rise', 'Decrease', 'Improve', 'c', 'The opposite of increase is decrease.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a recall exercise: Choose the antonym of "increase".', 'Grow', 'Rise', 'Decrease', 'Improve', 'c', 'The opposite of increase is decrease.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For a final check: Choose the antonym of "increase".', 'Grow', 'Rise', 'Decrease', 'Improve', 'c', 'The opposite of increase is decrease.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a topic-wise test: Choose the antonym of "increase".', 'Grow', 'Rise', 'Decrease', 'Improve', 'c', 'The opposite of increase is decrease.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For basic concept revision: Choose the antonym of "increase".', 'Grow', 'Rise', 'Decrease', 'Improve', 'c', 'The opposite of increase is decrease.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For easy memory: Choose the antonym of "increase".', 'Grow', 'Rise', 'Decrease', 'Improve', 'c', 'The opposite of increase is decrease.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a bedside review: Choose the antonym of "increase".', 'Grow', 'Rise', 'Decrease', 'Improve', 'c', 'The opposite of increase is decrease.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For study notes: Choose the antonym of "increase".', 'Grow', 'Rise', 'Decrease', 'Improve', 'c', 'The opposite of increase is decrease.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a revision round: Choose the antonym of "increase".', 'Grow', 'Rise', 'Decrease', 'Improve', 'c', 'The opposite of increase is decrease.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For a quick quiz: Choose the antonym of "increase".', 'Grow', 'Rise', 'Decrease', 'Improve', 'c', 'The opposite of increase is decrease.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In an MCQ session: Choose the antonym of "increase".', 'Grow', 'Rise', 'Decrease', 'Improve', 'c', 'The opposite of increase is decrease.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For practical preparation: Choose the antonym of "increase".', 'Grow', 'Rise', 'Decrease', 'Improve', 'c', 'The opposite of increase is decrease.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'As a quick reminder: Choose the antonym of "increase".', 'Grow', 'Rise', 'Decrease', 'Improve', 'c', 'The opposite of increase is decrease.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a serious revision: Choose the antonym of "increase".', 'Grow', 'Rise', 'Decrease', 'Improve', 'c', 'The opposite of increase is decrease.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For fast practice: Choose the antonym of "increase".', 'Grow', 'Rise', 'Decrease', 'Improve', 'c', 'The opposite of increase is decrease.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a focused session: Choose the antonym of "increase".', 'Grow', 'Rise', 'Decrease', 'Improve', 'c', 'The opposite of increase is decrease.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For exam confidence: Choose the antonym of "increase".', 'Grow', 'Rise', 'Decrease', 'Improve', 'c', 'The opposite of increase is decrease.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'During study time: Choose the antonym of "increase".', 'Grow', 'Rise', 'Decrease', 'Improve', 'c', 'The opposite of increase is decrease.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For a final look: Choose the antonym of "increase".', 'Grow', 'Rise', 'Decrease', 'Improve', 'c', 'The opposite of increase is decrease.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In an active recall session: Choose the antonym of "increase".', 'Grow', 'Rise', 'Decrease', 'Improve', 'c', 'The opposite of increase is decrease.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For a topic recap: Choose the antonym of "increase".', 'Grow', 'Rise', 'Decrease', 'Improve', 'c', 'The opposite of increase is decrease.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'In a fast review: Choose the antonym of "increase".', 'Grow', 'Rise', 'Decrease', 'Improve', 'c', 'The opposite of increase is decrease.', 'easy', TRUE),
('English', 'Synonyms and Antonyms', 'For high focus: Choose the antonym of "increase".', 'Grow', 'Rise', 'Decrease', 'Improve', 'c', 'The opposite of increase is decrease.', 'easy', TRUE);

COMMIT;
